#' AI Platform Training & Prediction API
#' An API to enable creating and using machine learning models.
#' 
#' Auto-generated code by googleAuthR::gar_create_api_skeleton
#'  at 2022-07-13 10:40:00
#' filename: /Users/justin/Sync/projects/github.com/justinjm/autoGoogleAPI/googlemlv1.auto/R/ml_functions.R
#' api_json: api_json
#' 
#' @details 
#' Authentication scopes used are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' \item https://www.googleapis.com/auth/cloud-platform.read-only
#' }
#' 
#' @docType package 
#' @name ml_googleAuthR
#' 
NULL
## NULL

#' A helper function that tests whether an object is either NULL _or_
#' a list of NULLs
#'
#' @keywords internal
is.NullOb <- function(x) is.null(x) | all(sapply(x, is.null))
#' Recursively step down into list, removing all such objects
#'
#' @keywords internal
rmNullObs <- function(x) {
    x <- Filter(Negate(is.NullOb), x)
    lapply(x, function(x) if (is.list(x))
        rmNullObs(x) else x)
}

#' Get the service account information associated with your project. You need this information in order to grant the service account permissions for the Google Cloud Storage location where you put your model training code for training the model with Google Cloud Machine Learning.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/ml/}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param name Required
#' @importFrom googleAuthR gar_api_generator
#' @export
projects.getConfig <- function(name) {
    url <- sprintf("https://ml.googleapis.com/v1/{+name}:getConfig", name)
    # ml.projects.getConfig
    f <- googleAuthR::gar_api_generator(url, "GET", data_parse_function = function(x) x)
    f()

}

#' Performs explanation on the data in the request. {% dynamic include '/ai-platform/includes/___explain-request' %} 
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/ml/}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param GoogleCloudMlV1__ExplainRequest The \link{GoogleCloudMlV1__ExplainRequest} object to pass to this method
#' @param name Required
#' @importFrom googleAuthR gar_api_generator
#' @family GoogleCloudMlV1__ExplainRequest functions
#' @export
projects.explain <- function(GoogleCloudMlV1__ExplainRequest, name) {
    url <- sprintf("https://ml.googleapis.com/v1/{+name}:explain", name)
    # ml.projects.explain
    f <- googleAuthR::gar_api_generator(url, "POST", data_parse_function = function(x) x)
    stopifnot(inherits(GoogleCloudMlV1__ExplainRequest, "gar_GoogleCloudMlV1__ExplainRequest"))

    f(the_body = GoogleCloudMlV1__ExplainRequest)

}

#' Performs online prediction on the data in the request. {% dynamic include '/ai-platform/includes/___predict-request' %} 
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/ml/}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param GoogleCloudMlV1__PredictRequest The \link{GoogleCloudMlV1__PredictRequest} object to pass to this method
#' @param name Required
#' @importFrom googleAuthR gar_api_generator
#' @family GoogleCloudMlV1__PredictRequest functions
#' @export
projects.predict <- function(GoogleCloudMlV1__PredictRequest, name) {
    url <- sprintf("https://ml.googleapis.com/v1/{+name}:predict", name)
    # ml.projects.predict
    f <- googleAuthR::gar_api_generator(url, "POST", data_parse_function = function(x) x)
    stopifnot(inherits(GoogleCloudMlV1__PredictRequest, "gar_GoogleCloudMlV1__PredictRequest"))

    f(the_body = GoogleCloudMlV1__PredictRequest)

}

#' List all locations that provides at least one type of CMLE capability.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/ml/}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' \item https://www.googleapis.com/auth/cloud-platform.read-only
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform, https://www.googleapis.com/auth/cloud-platform.read-only)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param parent Required
#' @param pageSize Optional
#' @param pageToken Optional
#' @importFrom googleAuthR gar_api_generator
#' @export
projects.locations.list <- function(parent, pageSize = NULL, pageToken = NULL) {
    url <- sprintf("https://ml.googleapis.com/v1/{+parent}/locations", parent)
    # ml.projects.locations.list
    pars = list(pageSize = pageSize, pageToken = pageToken)
    f <- googleAuthR::gar_api_generator(url, "GET", pars_args = rmNullObs(pars),
        data_parse_function = function(x) x)
    f()

}

#' Get the complete list of CMLE capabilities in a location, along with their location-specific properties.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/ml/}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' \item https://www.googleapis.com/auth/cloud-platform.read-only
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform, https://www.googleapis.com/auth/cloud-platform.read-only)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param name Required
#' @importFrom googleAuthR gar_api_generator
#' @export
projects.locations.get <- function(name) {
    url <- sprintf("https://ml.googleapis.com/v1/{+name}", name)
    # ml.projects.locations.get
    f <- googleAuthR::gar_api_generator(url, "GET", data_parse_function = function(x) x)
    f()

}

#' Lists all the studies in a region for an associated project.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/ml/}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param parent Required
#' @importFrom googleAuthR gar_api_generator
#' @export
projects.locations.studies.list <- function(parent) {
    url <- sprintf("https://ml.googleapis.com/v1/{+parent}/studies", parent)
    # ml.projects.locations.studies.list
    f <- googleAuthR::gar_api_generator(url, "GET", data_parse_function = function(x) x)
    f()

}

#' Creates a study.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/ml/}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param GoogleCloudMlV1__Study The \link{GoogleCloudMlV1__Study} object to pass to this method
#' @param parent Required
#' @param studyId Required
#' @importFrom googleAuthR gar_api_generator
#' @family GoogleCloudMlV1__Study functions
#' @export
projects.locations.studies.create <- function(GoogleCloudMlV1__Study, parent, studyId = NULL) {
    url <- sprintf("https://ml.googleapis.com/v1/{+parent}/studies", parent)
    # ml.projects.locations.studies.create
    pars = list(studyId = studyId)
    f <- googleAuthR::gar_api_generator(url, "POST", pars_args = rmNullObs(pars),
        data_parse_function = function(x) x)
    stopifnot(inherits(GoogleCloudMlV1__Study, "gar_GoogleCloudMlV1__Study"))

    f(the_body = GoogleCloudMlV1__Study)

}

#' Gets a study.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/ml/}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param name Required
#' @importFrom googleAuthR gar_api_generator
#' @export
projects.locations.studies.get <- function(name) {
    url <- sprintf("https://ml.googleapis.com/v1/{+name}", name)
    # ml.projects.locations.studies.get
    f <- googleAuthR::gar_api_generator(url, "GET", data_parse_function = function(x) x)
    f()

}

#' Deletes a study.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/ml/}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param name Required
#' @importFrom googleAuthR gar_api_generator
#' @export
projects.locations.studies.delete <- function(name) {
    url <- sprintf("https://ml.googleapis.com/v1/{+name}", name)
    # ml.projects.locations.studies.delete
    f <- googleAuthR::gar_api_generator(url, "DELETE", data_parse_function = function(x) x)
    f()

}

#' Adds one or more trials to a study, with parameter values suggested by AI Platform Vizier. Returns a long-running operation associated with the generation of trial suggestions. When this long-running operation succeeds, it will contain a SuggestTrialsResponse.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/ml/}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param GoogleCloudMlV1__SuggestTrialsRequest The \link{GoogleCloudMlV1__SuggestTrialsRequest} object to pass to this method
#' @param parent Required
#' @importFrom googleAuthR gar_api_generator
#' @family GoogleCloudMlV1__SuggestTrialsRequest functions
#' @export
projects.locations.studies.trials.suggest <- function(GoogleCloudMlV1__SuggestTrialsRequest,
    parent) {
    url <- sprintf("https://ml.googleapis.com/v1/{+parent}/trials:suggest", parent)
    # ml.projects.locations.studies.trials.suggest
    f <- googleAuthR::gar_api_generator(url, "POST", data_parse_function = function(x) x)
    stopifnot(inherits(GoogleCloudMlV1__SuggestTrialsRequest, "gar_GoogleCloudMlV1__SuggestTrialsRequest"))

    f(the_body = GoogleCloudMlV1__SuggestTrialsRequest)

}

#' Lists the trials associated with a study.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/ml/}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param parent Required
#' @importFrom googleAuthR gar_api_generator
#' @export
projects.locations.studies.trials.list <- function(parent) {
    url <- sprintf("https://ml.googleapis.com/v1/{+parent}/trials", parent)
    # ml.projects.locations.studies.trials.list
    f <- googleAuthR::gar_api_generator(url, "GET", data_parse_function = function(x) x)
    f()

}

#' Stops a trial.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/ml/}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param GoogleCloudMlV1__StopTrialRequest The \link{GoogleCloudMlV1__StopTrialRequest} object to pass to this method
#' @param name Required
#' @importFrom googleAuthR gar_api_generator
#' @family GoogleCloudMlV1__StopTrialRequest functions
#' @export
projects.locations.studies.trials.stop <- function(GoogleCloudMlV1__StopTrialRequest,
    name) {
    url <- sprintf("https://ml.googleapis.com/v1/{+name}:stop", name)
    # ml.projects.locations.studies.trials.stop
    f <- googleAuthR::gar_api_generator(url, "POST", data_parse_function = function(x) x)
    stopifnot(inherits(GoogleCloudMlV1__StopTrialRequest, "gar_GoogleCloudMlV1__StopTrialRequest"))

    f(the_body = GoogleCloudMlV1__StopTrialRequest)

}

#' Adds a measurement of the objective metrics to a trial. This measurement is assumed to have been taken before the trial is complete.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/ml/}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param GoogleCloudMlV1__AddTrialMeasurementRequest The \link{GoogleCloudMlV1__AddTrialMeasurementRequest} object to pass to this method
#' @param name Required
#' @importFrom googleAuthR gar_api_generator
#' @family GoogleCloudMlV1__AddTrialMeasurementRequest functions
#' @export
projects.locations.studies.trials.addMeasurement <- function(GoogleCloudMlV1__AddTrialMeasurementRequest,
    name) {
    url <- sprintf("https://ml.googleapis.com/v1/{+name}:addMeasurement", name)
    # ml.projects.locations.studies.trials.addMeasurement
    f <- googleAuthR::gar_api_generator(url, "POST", data_parse_function = function(x) x)
    stopifnot(inherits(GoogleCloudMlV1__AddTrialMeasurementRequest, "gar_GoogleCloudMlV1__AddTrialMeasurementRequest"))

    f(the_body = GoogleCloudMlV1__AddTrialMeasurementRequest)

}

#' Adds a user provided trial to a study.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/ml/}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param GoogleCloudMlV1__Trial The \link{GoogleCloudMlV1__Trial} object to pass to this method
#' @param parent Required
#' @importFrom googleAuthR gar_api_generator
#' @family GoogleCloudMlV1__Trial functions
#' @export
projects.locations.studies.trials.create <- function(GoogleCloudMlV1__Trial, parent) {
    url <- sprintf("https://ml.googleapis.com/v1/{+parent}/trials", parent)
    # ml.projects.locations.studies.trials.create
    f <- googleAuthR::gar_api_generator(url, "POST", data_parse_function = function(x) x)
    stopifnot(inherits(GoogleCloudMlV1__Trial, "gar_GoogleCloudMlV1__Trial"))

    f(the_body = GoogleCloudMlV1__Trial)

}

#' Lists the pareto-optimal trials for multi-objective study or the optimal trials for single-objective study. The definition of pareto-optimal can be checked in wiki page. https://en.wikipedia.org/wiki/Pareto_efficiency
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/ml/}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param GoogleCloudMlV1__ListOptimalTrialsRequest The \link{GoogleCloudMlV1__ListOptimalTrialsRequest} object to pass to this method
#' @param parent Required
#' @importFrom googleAuthR gar_api_generator
#' @family GoogleCloudMlV1__ListOptimalTrialsRequest functions
#' @export
projects.locations.studies.trials.listOptimalTrials <- function(GoogleCloudMlV1__ListOptimalTrialsRequest,
    parent) {
    url <- sprintf("https://ml.googleapis.com/v1/{+parent}/trials:listOptimalTrials",
        parent)
    # ml.projects.locations.studies.trials.listOptimalTrials
    f <- googleAuthR::gar_api_generator(url, "POST", data_parse_function = function(x) x)
    stopifnot(inherits(GoogleCloudMlV1__ListOptimalTrialsRequest, "gar_GoogleCloudMlV1__ListOptimalTrialsRequest"))

    f(the_body = GoogleCloudMlV1__ListOptimalTrialsRequest)

}

#' Gets a trial.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/ml/}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param name Required
#' @importFrom googleAuthR gar_api_generator
#' @export
projects.locations.studies.trials.get <- function(name) {
    url <- sprintf("https://ml.googleapis.com/v1/{+name}", name)
    # ml.projects.locations.studies.trials.get
    f <- googleAuthR::gar_api_generator(url, "GET", data_parse_function = function(x) x)
    f()

}

#' Checks whether a trial should stop or not. Returns a long-running operation. When the operation is successful, it will contain a CheckTrialEarlyStoppingStateResponse.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/ml/}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param GoogleCloudMlV1__CheckTrialEarlyStoppingStateRequest The \link{GoogleCloudMlV1__CheckTrialEarlyStoppingStateRequest} object to pass to this method
#' @param name Required
#' @importFrom googleAuthR gar_api_generator
#' @family GoogleCloudMlV1__CheckTrialEarlyStoppingStateRequest functions
#' @export
projects.locations.studies.trials.checkEarlyStoppingState <- function(GoogleCloudMlV1__CheckTrialEarlyStoppingStateRequest,
    name) {
    url <- sprintf("https://ml.googleapis.com/v1/{+name}:checkEarlyStoppingState",
        name)
    # ml.projects.locations.studies.trials.checkEarlyStoppingState
    f <- googleAuthR::gar_api_generator(url, "POST", data_parse_function = function(x) x)
    stopifnot(inherits(GoogleCloudMlV1__CheckTrialEarlyStoppingStateRequest, "gar_GoogleCloudMlV1__CheckTrialEarlyStoppingStateRequest"))

    f(the_body = GoogleCloudMlV1__CheckTrialEarlyStoppingStateRequest)

}

#' Deletes a trial.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/ml/}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param name Required
#' @importFrom googleAuthR gar_api_generator
#' @export
projects.locations.studies.trials.delete <- function(name) {
    url <- sprintf("https://ml.googleapis.com/v1/{+name}", name)
    # ml.projects.locations.studies.trials.delete
    f <- googleAuthR::gar_api_generator(url, "DELETE", data_parse_function = function(x) x)
    f()

}

#' Marks a trial as complete.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/ml/}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param GoogleCloudMlV1__CompleteTrialRequest The \link{GoogleCloudMlV1__CompleteTrialRequest} object to pass to this method
#' @param name Required
#' @importFrom googleAuthR gar_api_generator
#' @family GoogleCloudMlV1__CompleteTrialRequest functions
#' @export
projects.locations.studies.trials.complete <- function(GoogleCloudMlV1__CompleteTrialRequest,
    name) {
    url <- sprintf("https://ml.googleapis.com/v1/{+name}:complete", name)
    # ml.projects.locations.studies.trials.complete
    f <- googleAuthR::gar_api_generator(url, "POST", data_parse_function = function(x) x)
    stopifnot(inherits(GoogleCloudMlV1__CompleteTrialRequest, "gar_GoogleCloudMlV1__CompleteTrialRequest"))

    f(the_body = GoogleCloudMlV1__CompleteTrialRequest)

}

#' Starts asynchronous cancellation on a long-running operation. The server makes a best effort to cancel the operation, but success is not guaranteed. If the server doesn't support this method, it returns `google.rpc.Code.UNIMPLEMENTED`. Clients can use Operations.GetOperation or other methods to check whether the cancellation succeeded or whether the operation completed despite cancellation. On successful cancellation, the operation is not deleted; instead, it becomes an operation with an Operation.error value with a google.rpc.Status.code of 1, corresponding to `Code.CANCELLED`.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/ml/}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param name The name of the operation resource to be cancelled
#' @importFrom googleAuthR gar_api_generator
#' @export
projects.locations.operations.cancel <- function(name) {
    url <- sprintf("https://ml.googleapis.com/v1/{+name}:cancel", name)
    # ml.projects.locations.operations.cancel
    f <- googleAuthR::gar_api_generator(url, "POST", data_parse_function = function(x) x)
    f()

}

#' Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/ml/}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param name The name of the operation resource
#' @importFrom googleAuthR gar_api_generator
#' @export
projects.locations.operations.get <- function(name) {
    url <- sprintf("https://ml.googleapis.com/v1/{+name}", name)
    # ml.projects.locations.operations.get
    f <- googleAuthR::gar_api_generator(url, "GET", data_parse_function = function(x) x)
    f()

}

#' Gets the access control policy for a resource. Returns an empty policy if the resource exists and does not have a policy set.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/ml/}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param resource REQUIRED: The resource for which the policy is being requested
#' @param options.requestedPolicyVersion Optional
#' @importFrom googleAuthR gar_api_generator
#' @export
projects.models.getIamPolicy <- function(resource, options.requestedPolicyVersion = NULL) {
    url <- sprintf("https://ml.googleapis.com/v1/{+resource}:getIamPolicy", resource)
    # ml.projects.models.getIamPolicy
    pars = list(options.requestedPolicyVersion = options.requestedPolicyVersion)
    f <- googleAuthR::gar_api_generator(url, "GET", pars_args = rmNullObs(pars),
        data_parse_function = function(x) x)
    f()

}

#' Sets the access control policy on the specified resource. Replaces any existing policy. Can return `NOT_FOUND`, `INVALID_ARGUMENT`, and `PERMISSION_DENIED` errors.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/ml/}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param GoogleIamV1__SetIamPolicyRequest The \link{GoogleIamV1__SetIamPolicyRequest} object to pass to this method
#' @param resource REQUIRED: The resource for which the policy is being specified
#' @importFrom googleAuthR gar_api_generator
#' @family GoogleIamV1__SetIamPolicyRequest functions
#' @export
projects.models.setIamPolicy <- function(GoogleIamV1__SetIamPolicyRequest, resource) {
    url <- sprintf("https://ml.googleapis.com/v1/{+resource}:setIamPolicy", resource)
    # ml.projects.models.setIamPolicy
    f <- googleAuthR::gar_api_generator(url, "POST", data_parse_function = function(x) x)
    stopifnot(inherits(GoogleIamV1__SetIamPolicyRequest, "gar_GoogleIamV1__SetIamPolicyRequest"))

    f(the_body = GoogleIamV1__SetIamPolicyRequest)

}

#' Lists the models in a project. Each project can contain multiple models, and each model can have multiple versions. If there are no models that match the request parameters, the list request returns an empty response body: {}.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/ml/}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' \item https://www.googleapis.com/auth/cloud-platform.read-only
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform, https://www.googleapis.com/auth/cloud-platform.read-only)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param parent Required
#' @param pageSize Optional
#' @param pageToken Optional
#' @param filter Optional
#' @importFrom googleAuthR gar_api_generator
#' @export
projects.models.list <- function(parent, pageSize = NULL, pageToken = NULL, filter = NULL) {
    url <- sprintf("https://ml.googleapis.com/v1/{+parent}/models", parent)
    # ml.projects.models.list
    pars = list(pageSize = pageSize, pageToken = pageToken, filter = filter)
    f <- googleAuthR::gar_api_generator(url, "GET", pars_args = rmNullObs(pars),
        data_parse_function = function(x) x)
    f()

}

#' Updates a specific model resource. Currently the only supported fields to update are `description` and `default_version.name`.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/ml/}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param GoogleCloudMlV1__Model The \link{GoogleCloudMlV1__Model} object to pass to this method
#' @param name Required
#' @param updateMask Required
#' @importFrom googleAuthR gar_api_generator
#' @family GoogleCloudMlV1__Model functions
#' @export
projects.models.patch <- function(GoogleCloudMlV1__Model, name, updateMask = NULL) {
    url <- sprintf("https://ml.googleapis.com/v1/{+name}", name)
    # ml.projects.models.patch
    pars = list(updateMask = updateMask)
    f <- googleAuthR::gar_api_generator(url, "PATCH", pars_args = rmNullObs(pars),
        data_parse_function = function(x) x)
    stopifnot(inherits(GoogleCloudMlV1__Model, "gar_GoogleCloudMlV1__Model"))

    f(the_body = GoogleCloudMlV1__Model)

}

#' Returns permissions that a caller has on the specified resource. If the resource does not exist, this will return an empty set of permissions, not a `NOT_FOUND` error. Note: This operation is designed to be used for building permission-aware UIs and command-line tools, not for authorization checking. This operation may 'fail open' without warning.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/ml/}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param GoogleIamV1__TestIamPermissionsRequest The \link{GoogleIamV1__TestIamPermissionsRequest} object to pass to this method
#' @param resource REQUIRED: The resource for which the policy detail is being requested
#' @importFrom googleAuthR gar_api_generator
#' @family GoogleIamV1__TestIamPermissionsRequest functions
#' @export
projects.models.testIamPermissions <- function(GoogleIamV1__TestIamPermissionsRequest,
    resource) {
    url <- sprintf("https://ml.googleapis.com/v1/{+resource}:testIamPermissions",
        resource)
    # ml.projects.models.testIamPermissions
    f <- googleAuthR::gar_api_generator(url, "POST", data_parse_function = function(x) x)
    stopifnot(inherits(GoogleIamV1__TestIamPermissionsRequest, "gar_GoogleIamV1__TestIamPermissionsRequest"))

    f(the_body = GoogleIamV1__TestIamPermissionsRequest)

}

#' Gets information about a model, including its name, the description (if set), and the default version (if at least one version of the model has been deployed).
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/ml/}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' \item https://www.googleapis.com/auth/cloud-platform.read-only
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform, https://www.googleapis.com/auth/cloud-platform.read-only)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param name Required
#' @importFrom googleAuthR gar_api_generator
#' @export
projects.models.get <- function(name) {
    url <- sprintf("https://ml.googleapis.com/v1/{+name}", name)
    # ml.projects.models.get
    f <- googleAuthR::gar_api_generator(url, "GET", data_parse_function = function(x) x)
    f()

}

#' Creates a model which will later contain one or more versions. You must add at least one version before you can request predictions from the model. Add versions by calling projects.models.versions.create.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/ml/}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param GoogleCloudMlV1__Model The \link{GoogleCloudMlV1__Model} object to pass to this method
#' @param parent Required
#' @importFrom googleAuthR gar_api_generator
#' @family GoogleCloudMlV1__Model functions
#' @export
projects.models.create <- function(GoogleCloudMlV1__Model, parent) {
    url <- sprintf("https://ml.googleapis.com/v1/{+parent}/models", parent)
    # ml.projects.models.create
    f <- googleAuthR::gar_api_generator(url, "POST", data_parse_function = function(x) x)
    stopifnot(inherits(GoogleCloudMlV1__Model, "gar_GoogleCloudMlV1__Model"))

    f(the_body = GoogleCloudMlV1__Model)

}

#' Deletes a model. You can only delete a model if there are no versions in it. You can delete versions by calling projects.models.versions.delete.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/ml/}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param name Required
#' @importFrom googleAuthR gar_api_generator
#' @export
projects.models.delete <- function(name) {
    url <- sprintf("https://ml.googleapis.com/v1/{+name}", name)
    # ml.projects.models.delete
    f <- googleAuthR::gar_api_generator(url, "DELETE", data_parse_function = function(x) x)
    f()

}

#' Gets information about a model version. Models can have multiple versions. You can call projects.models.versions.list to get the same information that this method returns for all of the versions of a model.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/ml/}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param name Required
#' @importFrom googleAuthR gar_api_generator
#' @export
projects.models.versions.get <- function(name) {
    url <- sprintf("https://ml.googleapis.com/v1/{+name}", name)
    # ml.projects.models.versions.get
    f <- googleAuthR::gar_api_generator(url, "GET", data_parse_function = function(x) x)
    f()

}

#' Gets basic information about all the versions of a model. If you expect that a model has many versions, or if you need to handle only a limited number of results at a time, you can request that the list be retrieved in batches (called pages). If there are no versions that match the request parameters, the list request returns an empty response body: {}.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/ml/}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' \item https://www.googleapis.com/auth/cloud-platform.read-only
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform, https://www.googleapis.com/auth/cloud-platform.read-only)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param parent Required
#' @param pageToken Optional
#' @param filter Optional
#' @param pageSize Optional
#' @importFrom googleAuthR gar_api_generator
#' @export
projects.models.versions.list <- function(parent, pageToken = NULL, filter = NULL,
    pageSize = NULL) {
    url <- sprintf("https://ml.googleapis.com/v1/{+parent}/versions", parent)
    # ml.projects.models.versions.list
    pars = list(pageToken = pageToken, filter = filter, pageSize = pageSize)
    f <- googleAuthR::gar_api_generator(url, "GET", pars_args = rmNullObs(pars),
        data_parse_function = function(x) x)
    f()

}

#' Deletes a model version. Each model can have multiple versions deployed and in use at any given time. Use this method to remove a single version. Note: You cannot delete the version that is set as the default version of the model unless it is the only remaining version.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/ml/}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param name Required
#' @importFrom googleAuthR gar_api_generator
#' @export
projects.models.versions.delete <- function(name) {
    url <- sprintf("https://ml.googleapis.com/v1/{+name}", name)
    # ml.projects.models.versions.delete
    f <- googleAuthR::gar_api_generator(url, "DELETE", data_parse_function = function(x) x)
    f()

}

#' Designates a version to be the default for the model. The default version is used for prediction requests made against the model that don't specify a version. The first version to be created for a model is automatically set as the default. You must make any subsequent changes to the default version setting manually using this method.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/ml/}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param GoogleCloudMlV1__SetDefaultVersionRequest The \link{GoogleCloudMlV1__SetDefaultVersionRequest} object to pass to this method
#' @param name Required
#' @importFrom googleAuthR gar_api_generator
#' @family GoogleCloudMlV1__SetDefaultVersionRequest functions
#' @export
projects.models.versions.setDefault <- function(GoogleCloudMlV1__SetDefaultVersionRequest,
    name) {
    url <- sprintf("https://ml.googleapis.com/v1/{+name}:setDefault", name)
    # ml.projects.models.versions.setDefault
    f <- googleAuthR::gar_api_generator(url, "POST", data_parse_function = function(x) x)
    stopifnot(inherits(GoogleCloudMlV1__SetDefaultVersionRequest, "gar_GoogleCloudMlV1__SetDefaultVersionRequest"))

    f(the_body = GoogleCloudMlV1__SetDefaultVersionRequest)

}

#' Updates the specified Version resource. Currently the only update-able fields are `description`, `requestLoggingConfig`, `autoScaling.minNodes`, and `manualScaling.nodes`.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/ml/}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param GoogleCloudMlV1__Version The \link{GoogleCloudMlV1__Version} object to pass to this method
#' @param name Required
#' @param updateMask Required
#' @importFrom googleAuthR gar_api_generator
#' @family GoogleCloudMlV1__Version functions
#' @export
projects.models.versions.patch <- function(GoogleCloudMlV1__Version, name, updateMask = NULL) {
    url <- sprintf("https://ml.googleapis.com/v1/{+name}", name)
    # ml.projects.models.versions.patch
    pars = list(updateMask = updateMask)
    f <- googleAuthR::gar_api_generator(url, "PATCH", pars_args = rmNullObs(pars),
        data_parse_function = function(x) x)
    stopifnot(inherits(GoogleCloudMlV1__Version, "gar_GoogleCloudMlV1__Version"))

    f(the_body = GoogleCloudMlV1__Version)

}

#' Creates a new version of a model from a trained TensorFlow model. If the version created in the cloud by this call is the first deployed version of the specified model, it will be made the default version of the model. When you add a version to a model that already has one or more versions, the default version does not automatically change. If you want a new version to be the default, you must call projects.models.versions.setDefault.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/ml/}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param GoogleCloudMlV1__Version The \link{GoogleCloudMlV1__Version} object to pass to this method
#' @param parent Required
#' @importFrom googleAuthR gar_api_generator
#' @family GoogleCloudMlV1__Version functions
#' @export
projects.models.versions.create <- function(GoogleCloudMlV1__Version, parent) {
    url <- sprintf("https://ml.googleapis.com/v1/{+parent}/versions", parent)
    # ml.projects.models.versions.create
    f <- googleAuthR::gar_api_generator(url, "POST", data_parse_function = function(x) x)
    stopifnot(inherits(GoogleCloudMlV1__Version, "gar_GoogleCloudMlV1__Version"))

    f(the_body = GoogleCloudMlV1__Version)

}

#' Starts asynchronous cancellation on a long-running operation. The server makes a best effort to cancel the operation, but success is not guaranteed. If the server doesn't support this method, it returns `google.rpc.Code.UNIMPLEMENTED`. Clients can use Operations.GetOperation or other methods to check whether the cancellation succeeded or whether the operation completed despite cancellation. On successful cancellation, the operation is not deleted; instead, it becomes an operation with an Operation.error value with a google.rpc.Status.code of 1, corresponding to `Code.CANCELLED`.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/ml/}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param name The name of the operation resource to be cancelled
#' @importFrom googleAuthR gar_api_generator
#' @export
projects.operations.cancel <- function(name) {
    url <- sprintf("https://ml.googleapis.com/v1/{+name}:cancel", name)
    # ml.projects.operations.cancel
    f <- googleAuthR::gar_api_generator(url, "POST", data_parse_function = function(x) x)
    f()

}

#' Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`. NOTE: the `name` binding allows API services to override the binding to use different resource name schemes, such as `users/*/operations`. To override the binding, API services can add a binding such as `'/v1/{name=users/*}/operations'` to their service configuration. For backwards compatibility, the default name includes the operations collection id, however overriding users must ensure the name binding is the parent resource, without the operations collection id.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/ml/}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param name The name of the operation's parent resource
#' @param filter The standard list filter
#' @param pageToken The standard list page token
#' @param pageSize The standard list page size
#' @importFrom googleAuthR gar_api_generator
#' @export
projects.operations.list <- function(name, filter = NULL, pageToken = NULL, pageSize = NULL) {
    url <- sprintf("https://ml.googleapis.com/v1/{+name}/operations", name)
    # ml.projects.operations.list
    pars = list(filter = filter, pageToken = pageToken, pageSize = pageSize)
    f <- googleAuthR::gar_api_generator(url, "GET", pars_args = rmNullObs(pars),
        data_parse_function = function(x) x)
    f()

}

#' Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/ml/}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param name The name of the operation resource
#' @importFrom googleAuthR gar_api_generator
#' @export
projects.operations.get <- function(name) {
    url <- sprintf("https://ml.googleapis.com/v1/{+name}", name)
    # ml.projects.operations.get
    f <- googleAuthR::gar_api_generator(url, "GET", data_parse_function = function(x) x)
    f()

}

#' Describes a job.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/ml/}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' \item https://www.googleapis.com/auth/cloud-platform.read-only
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform, https://www.googleapis.com/auth/cloud-platform.read-only)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param name Required
#' @importFrom googleAuthR gar_api_generator
#' @export
projects.jobs.get <- function(name) {
    url <- sprintf("https://ml.googleapis.com/v1/{+name}", name)
    # ml.projects.jobs.get
    f <- googleAuthR::gar_api_generator(url, "GET", data_parse_function = function(x) x)
    f()

}

#' Cancels a running job.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/ml/}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param GoogleCloudMlV1__CancelJobRequest The \link{GoogleCloudMlV1__CancelJobRequest} object to pass to this method
#' @param name Required
#' @importFrom googleAuthR gar_api_generator
#' @family GoogleCloudMlV1__CancelJobRequest functions
#' @export
projects.jobs.cancel <- function(GoogleCloudMlV1__CancelJobRequest, name) {
    url <- sprintf("https://ml.googleapis.com/v1/{+name}:cancel", name)
    # ml.projects.jobs.cancel
    f <- googleAuthR::gar_api_generator(url, "POST", data_parse_function = function(x) x)
    stopifnot(inherits(GoogleCloudMlV1__CancelJobRequest, "gar_GoogleCloudMlV1__CancelJobRequest"))

    f(the_body = GoogleCloudMlV1__CancelJobRequest)

}

#' Sets the access control policy on the specified resource. Replaces any existing policy. Can return `NOT_FOUND`, `INVALID_ARGUMENT`, and `PERMISSION_DENIED` errors.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/ml/}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param GoogleIamV1__SetIamPolicyRequest The \link{GoogleIamV1__SetIamPolicyRequest} object to pass to this method
#' @param resource REQUIRED: The resource for which the policy is being specified
#' @importFrom googleAuthR gar_api_generator
#' @family GoogleIamV1__SetIamPolicyRequest functions
#' @export
projects.jobs.setIamPolicy <- function(GoogleIamV1__SetIamPolicyRequest, resource) {
    url <- sprintf("https://ml.googleapis.com/v1/{+resource}:setIamPolicy", resource)
    # ml.projects.jobs.setIamPolicy
    f <- googleAuthR::gar_api_generator(url, "POST", data_parse_function = function(x) x)
    stopifnot(inherits(GoogleIamV1__SetIamPolicyRequest, "gar_GoogleIamV1__SetIamPolicyRequest"))

    f(the_body = GoogleIamV1__SetIamPolicyRequest)

}

#' Updates a specific job resource. Currently the only supported fields to update are `labels`.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/ml/}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param GoogleCloudMlV1__Job The \link{GoogleCloudMlV1__Job} object to pass to this method
#' @param name Required
#' @param updateMask Required
#' @importFrom googleAuthR gar_api_generator
#' @family GoogleCloudMlV1__Job functions
#' @export
projects.jobs.patch <- function(GoogleCloudMlV1__Job, name, updateMask = NULL) {
    url <- sprintf("https://ml.googleapis.com/v1/{+name}", name)
    # ml.projects.jobs.patch
    pars = list(updateMask = updateMask)
    f <- googleAuthR::gar_api_generator(url, "PATCH", pars_args = rmNullObs(pars),
        data_parse_function = function(x) x)
    stopifnot(inherits(GoogleCloudMlV1__Job, "gar_GoogleCloudMlV1__Job"))

    f(the_body = GoogleCloudMlV1__Job)

}

#' Returns permissions that a caller has on the specified resource. If the resource does not exist, this will return an empty set of permissions, not a `NOT_FOUND` error. Note: This operation is designed to be used for building permission-aware UIs and command-line tools, not for authorization checking. This operation may 'fail open' without warning.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/ml/}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param GoogleIamV1__TestIamPermissionsRequest The \link{GoogleIamV1__TestIamPermissionsRequest} object to pass to this method
#' @param resource REQUIRED: The resource for which the policy detail is being requested
#' @importFrom googleAuthR gar_api_generator
#' @family GoogleIamV1__TestIamPermissionsRequest functions
#' @export
projects.jobs.testIamPermissions <- function(GoogleIamV1__TestIamPermissionsRequest,
    resource) {
    url <- sprintf("https://ml.googleapis.com/v1/{+resource}:testIamPermissions",
        resource)
    # ml.projects.jobs.testIamPermissions
    f <- googleAuthR::gar_api_generator(url, "POST", data_parse_function = function(x) x)
    stopifnot(inherits(GoogleIamV1__TestIamPermissionsRequest, "gar_GoogleIamV1__TestIamPermissionsRequest"))

    f(the_body = GoogleIamV1__TestIamPermissionsRequest)

}

#' Creates a training or a batch prediction job.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/ml/}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param GoogleCloudMlV1__Job The \link{GoogleCloudMlV1__Job} object to pass to this method
#' @param parent Required
#' @importFrom googleAuthR gar_api_generator
#' @family GoogleCloudMlV1__Job functions
#' @export
projects.jobs.create <- function(GoogleCloudMlV1__Job, parent) {
    url <- sprintf("https://ml.googleapis.com/v1/{+parent}/jobs", parent)
    # ml.projects.jobs.create
    f <- googleAuthR::gar_api_generator(url, "POST", data_parse_function = function(x) x)
    stopifnot(inherits(GoogleCloudMlV1__Job, "gar_GoogleCloudMlV1__Job"))

    f(the_body = GoogleCloudMlV1__Job)

}

#' Gets the access control policy for a resource. Returns an empty policy if the resource exists and does not have a policy set.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/ml/}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param resource REQUIRED: The resource for which the policy is being requested
#' @param options.requestedPolicyVersion Optional
#' @importFrom googleAuthR gar_api_generator
#' @export
projects.jobs.getIamPolicy <- function(resource, options.requestedPolicyVersion = NULL) {
    url <- sprintf("https://ml.googleapis.com/v1/{+resource}:getIamPolicy", resource)
    # ml.projects.jobs.getIamPolicy
    pars = list(options.requestedPolicyVersion = options.requestedPolicyVersion)
    f <- googleAuthR::gar_api_generator(url, "GET", pars_args = rmNullObs(pars),
        data_parse_function = function(x) x)
    f()

}


#' Lists the jobs in the project. If there are no jobs that match the request parameters, the list request returns an empty response body: {}.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/ml/}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' \item https://www.googleapis.com/auth/cloud-platform.read-only
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform, https://www.googleapis.com/auth/cloud-platform.read-only)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param parent Required

#' @param pageSize Optional

#' @param pageToken Optional

#' @param filter Optional
#' @importFrom googleAuthR gar_api_generator
#' @export


projects.jobs.list <- function(parent, pageSize = NULL, pageToken = NULL, filter = NULL) {


    url <- sprintf("https://ml.googleapis.com/v1/{+parent}/jobs", parent)
    # ml.projects.jobs.list
    pars = list(pageSize = pageSize, pageToken = pageToken, filter = filter)

    f <- googleAuthR::gar_api_generator(url, "GET", pars_args = rmNullObs(pars),
        data_parse_function = function(x) x)

    f()


}



