#' Cloud AutoML API
#' Train high-quality custom machine learning models with minimum effort and machine learning expertise.
#' 
#' Auto-generated code by googleAuthR::gar_create_api_skeleton
#'  at 2021-09-09 11:16:18
#' filename: /Users/justin/dev/R/autoGoogleAPI/googleautomlv1.auto/R/automl_functions.R
#' api_json: api_json
#' 
#' @details 
#' Authentication scopes used are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#' 
#' @docType package 
#' @name automl_googleAuthR
#' 
NULL
## NULL

#' A helper function that tests whether an object is either NULL _or_
#' a list of NULLs
#'
#' @keywords internal
is.NullOb <- function(x) is.null(x) | all(sapply(x, is.null))
#' Recursively step down into list, removing all such objects
#'
#' @keywords internal
rmNullObs <- function(x) {
    x <- Filter(Negate(is.NullOb), x)
    lapply(x, function(x) if (is.list(x)) 
        rmNullObs(x) else x)
}

#' Gets the access control policy for a resource. Returns an empty policy if the resource exists and does not have a policy set.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/automl}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param resource REQUIRED: The resource for which the policy is being requested
#' @param options.requestedPolicyVersion Optional
#' @importFrom googleAuthR gar_api_generator
#' @export
projects.locations.getIamPolicy <- function(resource, options.requestedPolicyVersion = NULL) {
    url <- sprintf("https://automl.googleapis.com/v1/{+resource}:getIamPolicy", resource)
    # automl.projects.locations.getIamPolicy
    pars = list(options.requestedPolicyVersion = options.requestedPolicyVersion)
    f <- googleAuthR::gar_api_generator(url, "GET", pars_args = rmNullObs(pars), 
        data_parse_function = function(x) x)
    f()
    
}

#' Lists information about the supported locations for this service.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/automl}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param name The resource that owns the locations collection, if applicable
#' @param pageSize The maximum number of results to return
#' @param filter A filter to narrow down results to a preferred subset
#' @param pageToken A page token received from the `next_page_token` field in the response
#' @importFrom googleAuthR gar_api_generator
#' @export
projects.locations.list <- function(name, pageSize = NULL, filter = NULL, pageToken = NULL) {
    url <- sprintf("https://automl.googleapis.com/v1/{+name}/locations", name)
    # automl.projects.locations.list
    pars = list(pageSize = pageSize, filter = filter, pageToken = pageToken)
    f <- googleAuthR::gar_api_generator(url, "GET", pars_args = rmNullObs(pars), 
        data_parse_function = function(x) x)
    f()
    
}

#' Returns permissions that a caller has on the specified resource. If the resource does not exist, this will return an empty set of permissions, not a `NOT_FOUND` error. Note: This operation is designed to be used for building permission-aware UIs and command-line tools, not for authorization checking. This operation may 'fail open' without warning.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/automl}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param TestIamPermissionsRequest The \link{TestIamPermissionsRequest} object to pass to this method
#' @param resource REQUIRED: The resource for which the policy detail is being requested
#' @importFrom googleAuthR gar_api_generator
#' @family TestIamPermissionsRequest functions
#' @export
projects.locations.testIamPermissions <- function(TestIamPermissionsRequest, resource) {
    url <- sprintf("https://automl.googleapis.com/v1/{+resource}:testIamPermissions", 
        resource)
    # automl.projects.locations.testIamPermissions
    f <- googleAuthR::gar_api_generator(url, "POST", data_parse_function = function(x) x)
    stopifnot(inherits(TestIamPermissionsRequest, "gar_TestIamPermissionsRequest"))
    
    f(the_body = TestIamPermissionsRequest)
    
}

#' Gets information about a location.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/automl}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param name Resource name for the location
#' @importFrom googleAuthR gar_api_generator
#' @export
projects.locations.get <- function(name) {
    url <- sprintf("https://automl.googleapis.com/v1/{+name}", name)
    # automl.projects.locations.get
    f <- googleAuthR::gar_api_generator(url, "GET", data_parse_function = function(x) x)
    f()
    
}

#' Sets the access control policy on the specified resource. Replaces any existing policy. Can return `NOT_FOUND`, `INVALID_ARGUMENT`, and `PERMISSION_DENIED` errors.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/automl}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param SetIamPolicyRequest The \link{SetIamPolicyRequest} object to pass to this method
#' @param resource REQUIRED: The resource for which the policy is being specified
#' @importFrom googleAuthR gar_api_generator
#' @family SetIamPolicyRequest functions
#' @export
projects.locations.setIamPolicy <- function(SetIamPolicyRequest, resource) {
    url <- sprintf("https://automl.googleapis.com/v1/{+resource}:setIamPolicy", resource)
    # automl.projects.locations.setIamPolicy
    f <- googleAuthR::gar_api_generator(url, "POST", data_parse_function = function(x) x)
    stopifnot(inherits(SetIamPolicyRequest, "gar_SetIamPolicyRequest"))
    
    f(the_body = SetIamPolicyRequest)
    
}

#' Creates a dataset.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/automl}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param Dataset The \link{Dataset} object to pass to this method
#' @param parent Required
#' @importFrom googleAuthR gar_api_generator
#' @family Dataset functions
#' @export
projects.locations.datasets.create <- function(Dataset, parent) {
    url <- sprintf("https://automl.googleapis.com/v1/{+parent}/datasets", parent)
    # automl.projects.locations.datasets.create
    f <- googleAuthR::gar_api_generator(url, "POST", data_parse_function = function(x) x)
    stopifnot(inherits(Dataset, "gar_Dataset"))
    
    f(the_body = Dataset)
    
}

#' Imports data into a dataset. For Tables this method can only be called on an empty Dataset. For Tables: * A schema_inference_version parameter must be explicitly set. Returns an empty response in the response field when it completes.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/automl}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param ImportDataRequest The \link{ImportDataRequest} object to pass to this method
#' @param name Required
#' @importFrom googleAuthR gar_api_generator
#' @family ImportDataRequest functions
#' @export
projects.locations.datasets.importData <- function(ImportDataRequest, name) {
    url <- sprintf("https://automl.googleapis.com/v1/{+name}:importData", name)
    # automl.projects.locations.datasets.importData
    f <- googleAuthR::gar_api_generator(url, "POST", data_parse_function = function(x) x)
    stopifnot(inherits(ImportDataRequest, "gar_ImportDataRequest"))
    
    f(the_body = ImportDataRequest)
    
}

#' Deletes a dataset and all of its contents. Returns empty response in the response field when it completes, and `delete_details` in the metadata field.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/automl}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param name Required
#' @importFrom googleAuthR gar_api_generator
#' @export
projects.locations.datasets.delete <- function(name) {
    url <- sprintf("https://automl.googleapis.com/v1/{+name}", name)
    # automl.projects.locations.datasets.delete
    f <- googleAuthR::gar_api_generator(url, "DELETE", data_parse_function = function(x) x)
    f()
    
}

#' Exports dataset's data to the provided output location. Returns an empty response in the response field when it completes.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/automl}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param ExportDataRequest The \link{ExportDataRequest} object to pass to this method
#' @param name Required
#' @importFrom googleAuthR gar_api_generator
#' @family ExportDataRequest functions
#' @export
projects.locations.datasets.exportData <- function(ExportDataRequest, name) {
    url <- sprintf("https://automl.googleapis.com/v1/{+name}:exportData", name)
    # automl.projects.locations.datasets.exportData
    f <- googleAuthR::gar_api_generator(url, "POST", data_parse_function = function(x) x)
    stopifnot(inherits(ExportDataRequest, "gar_ExportDataRequest"))
    
    f(the_body = ExportDataRequest)
    
}

#' Updates a dataset.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/automl}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param Dataset The \link{Dataset} object to pass to this method
#' @param name Output only
#' @param updateMask Required
#' @importFrom googleAuthR gar_api_generator
#' @family Dataset functions
#' @export
projects.locations.datasets.patch <- function(Dataset, name, updateMask = NULL) {
    url <- sprintf("https://automl.googleapis.com/v1/{+name}", name)
    # automl.projects.locations.datasets.patch
    pars = list(updateMask = updateMask)
    f <- googleAuthR::gar_api_generator(url, "PATCH", pars_args = rmNullObs(pars), 
        data_parse_function = function(x) x)
    stopifnot(inherits(Dataset, "gar_Dataset"))
    
    f(the_body = Dataset)
    
}

#' Gets a dataset.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/automl}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param name Required
#' @importFrom googleAuthR gar_api_generator
#' @export
projects.locations.datasets.get <- function(name) {
    url <- sprintf("https://automl.googleapis.com/v1/{+name}", name)
    # automl.projects.locations.datasets.get
    f <- googleAuthR::gar_api_generator(url, "GET", data_parse_function = function(x) x)
    f()
    
}

#' Sets the access control policy on the specified resource. Replaces any existing policy. Can return `NOT_FOUND`, `INVALID_ARGUMENT`, and `PERMISSION_DENIED` errors.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/automl}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param SetIamPolicyRequest The \link{SetIamPolicyRequest} object to pass to this method
#' @param resource REQUIRED: The resource for which the policy is being specified
#' @importFrom googleAuthR gar_api_generator
#' @family SetIamPolicyRequest functions
#' @export
projects.locations.datasets.setIamPolicy <- function(SetIamPolicyRequest, resource) {
    url <- sprintf("https://automl.googleapis.com/v1/{+resource}:setIamPolicy", resource)
    # automl.projects.locations.datasets.setIamPolicy
    f <- googleAuthR::gar_api_generator(url, "POST", data_parse_function = function(x) x)
    stopifnot(inherits(SetIamPolicyRequest, "gar_SetIamPolicyRequest"))
    
    f(the_body = SetIamPolicyRequest)
    
}

#' Gets the access control policy for a resource. Returns an empty policy if the resource exists and does not have a policy set.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/automl}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param resource REQUIRED: The resource for which the policy is being requested
#' @param options.requestedPolicyVersion Optional
#' @importFrom googleAuthR gar_api_generator
#' @export
projects.locations.datasets.getIamPolicy <- function(resource, options.requestedPolicyVersion = NULL) {
    url <- sprintf("https://automl.googleapis.com/v1/{+resource}:getIamPolicy", resource)
    # automl.projects.locations.datasets.getIamPolicy
    pars = list(options.requestedPolicyVersion = options.requestedPolicyVersion)
    f <- googleAuthR::gar_api_generator(url, "GET", pars_args = rmNullObs(pars), 
        data_parse_function = function(x) x)
    f()
    
}

#' Lists datasets in a project.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/automl}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param parent Required
#' @param pageSize Requested page size
#' @param filter An expression for filtering the results of the request
#' @param pageToken A token identifying a page of results for the server to return Typically obtained via ListDatasetsResponse
#' @importFrom googleAuthR gar_api_generator
#' @export
projects.locations.datasets.list <- function(parent, pageSize = NULL, filter = NULL, 
    pageToken = NULL) {
    url <- sprintf("https://automl.googleapis.com/v1/{+parent}/datasets", parent)
    # automl.projects.locations.datasets.list
    pars = list(pageSize = pageSize, filter = filter, pageToken = pageToken)
    f <- googleAuthR::gar_api_generator(url, "GET", pars_args = rmNullObs(pars), 
        data_parse_function = function(x) x)
    f()
    
}

#' Gets an annotation spec.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/automl}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param name Required
#' @importFrom googleAuthR gar_api_generator
#' @export
projects.locations.datasets.annotationSpecs.get <- function(name) {
    url <- sprintf("https://automl.googleapis.com/v1/{+name}", name)
    # automl.projects.locations.datasets.annotationSpecs.get
    f <- googleAuthR::gar_api_generator(url, "GET", data_parse_function = function(x) x)
    f()
    
}

#' Starts asynchronous cancellation on a long-running operation. The server makes a best effort to cancel the operation, but success is not guaranteed. If the server doesn't support this method, it returns `google.rpc.Code.UNIMPLEMENTED`. Clients can use Operations.GetOperation or other methods to check whether the cancellation succeeded or whether the operation completed despite cancellation. On successful cancellation, the operation is not deleted; instead, it becomes an operation with an Operation.error value with a google.rpc.Status.code of 1, corresponding to `Code.CANCELLED`.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/automl}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param CancelOperationRequest The \link{CancelOperationRequest} object to pass to this method
#' @param name The name of the operation resource to be cancelled
#' @importFrom googleAuthR gar_api_generator
#' @family CancelOperationRequest functions
#' @export
projects.locations.operations.cancel <- function(CancelOperationRequest, name) {
    url <- sprintf("https://automl.googleapis.com/v1/{+name}:cancel", name)
    # automl.projects.locations.operations.cancel
    f <- googleAuthR::gar_api_generator(url, "POST", data_parse_function = function(x) x)
    stopifnot(inherits(CancelOperationRequest, "gar_CancelOperationRequest"))
    
    f(the_body = CancelOperationRequest)
    
}

#' Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`. NOTE: the `name` binding allows API services to override the binding to use different resource name schemes, such as `users/*/operations`. To override the binding, API services can add a binding such as `'/v1/{name=users/*}/operations'` to their service configuration. For backwards compatibility, the default name includes the operations collection id, however overriding users must ensure the name binding is the parent resource, without the operations collection id.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/automl}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param name The name of the operation's parent resource
#' @param pageSize The standard list page size
#' @param pageToken The standard list page token
#' @param filter An expression for filtering the results of the request
#' @importFrom googleAuthR gar_api_generator
#' @export
projects.locations.operations.list <- function(name, pageSize = NULL, pageToken = NULL, 
    filter = NULL) {
    url <- sprintf("https://automl.googleapis.com/v1/{+name}/operations", name)
    # automl.projects.locations.operations.list
    pars = list(pageSize = pageSize, pageToken = pageToken, filter = filter)
    f <- googleAuthR::gar_api_generator(url, "GET", pars_args = rmNullObs(pars), 
        data_parse_function = function(x) x)
    f()
    
}

#' Waits until the specified long-running operation is done or reaches at most a specified timeout, returning the latest state. If the operation is already done, the latest state is immediately returned. If the timeout specified is greater than the default HTTP/RPC timeout, the HTTP/RPC timeout is used. If the server does not support this method, it returns `google.rpc.Code.UNIMPLEMENTED`. Note that this method is on a best-effort basis. It may return the latest state before the specified timeout (including immediately), meaning even an immediate response is no guarantee that the operation is done.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/automl}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param WaitOperationRequest The \link{WaitOperationRequest} object to pass to this method
#' @param name The name of the operation resource to wait on
#' @importFrom googleAuthR gar_api_generator
#' @family WaitOperationRequest functions
#' @export
projects.locations.operations.wait <- function(WaitOperationRequest, name) {
    url <- sprintf("https://automl.googleapis.com/v1/{+name}:wait", name)
    # automl.projects.locations.operations.wait
    f <- googleAuthR::gar_api_generator(url, "POST", data_parse_function = function(x) x)
    stopifnot(inherits(WaitOperationRequest, "gar_WaitOperationRequest"))
    
    f(the_body = WaitOperationRequest)
    
}

#' Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/automl}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param name The name of the operation resource
#' @importFrom googleAuthR gar_api_generator
#' @export
projects.locations.operations.get <- function(name) {
    url <- sprintf("https://automl.googleapis.com/v1/{+name}", name)
    # automl.projects.locations.operations.get
    f <- googleAuthR::gar_api_generator(url, "GET", data_parse_function = function(x) x)
    f()
    
}

#' Deletes a long-running operation. This method indicates that the client is no longer interested in the operation result. It does not cancel the operation. If the server doesn't support this method, it returns `google.rpc.Code.UNIMPLEMENTED`.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/automl}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param name The name of the operation resource to be deleted
#' @importFrom googleAuthR gar_api_generator
#' @export
projects.locations.operations.delete <- function(name) {
    url <- sprintf("https://automl.googleapis.com/v1/{+name}", name)
    # automl.projects.locations.operations.delete
    f <- googleAuthR::gar_api_generator(url, "DELETE", data_parse_function = function(x) x)
    f()
    
}

#' Undeploys a model. If the model is not deployed this method has no effect. Only applicable for Text Classification, Image Object Detection and Tables; all other domains manage deployment automatically. Returns an empty response in the response field when it completes.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/automl}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param UndeployModelRequest The \link{UndeployModelRequest} object to pass to this method
#' @param name Required
#' @importFrom googleAuthR gar_api_generator
#' @family UndeployModelRequest functions
#' @export
projects.locations.models.undeploy <- function(UndeployModelRequest, name) {
    url <- sprintf("https://automl.googleapis.com/v1/{+name}:undeploy", name)
    # automl.projects.locations.models.undeploy
    f <- googleAuthR::gar_api_generator(url, "POST", data_parse_function = function(x) x)
    stopifnot(inherits(UndeployModelRequest, "gar_UndeployModelRequest"))
    
    f(the_body = UndeployModelRequest)
    
}

#' Deletes a model. Returns `google.protobuf.Empty` in the response field when it completes, and `delete_details` in the metadata field.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/automl}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param name Required
#' @importFrom googleAuthR gar_api_generator
#' @export
projects.locations.models.delete <- function(name) {
    url <- sprintf("https://automl.googleapis.com/v1/{+name}", name)
    # automl.projects.locations.models.delete
    f <- googleAuthR::gar_api_generator(url, "DELETE", data_parse_function = function(x) x)
    f()
    
}

#' Perform a batch prediction. Unlike the online Predict, batch prediction result won't be immediately available in the response. Instead, a long running operation object is returned. User can poll the operation result via GetOperation method. Once the operation is done, BatchPredictResult is returned in the response field. Available for following ML scenarios: * AutoML Vision Classification * AutoML Vision Object Detection * AutoML Video Intelligence Classification * AutoML Video Intelligence Object Tracking * AutoML Natural Language Classification * AutoML Natural Language Entity Extraction * AutoML Natural Language Sentiment Analysis * AutoML Tables
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/automl}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param BatchPredictRequest The \link{BatchPredictRequest} object to pass to this method
#' @param name Required
#' @importFrom googleAuthR gar_api_generator
#' @family BatchPredictRequest functions
#' @export
projects.locations.models.batchPredict <- function(BatchPredictRequest, name) {
    url <- sprintf("https://automl.googleapis.com/v1/{+name}:batchPredict", name)
    # automl.projects.locations.models.batchPredict
    f <- googleAuthR::gar_api_generator(url, "POST", data_parse_function = function(x) x)
    stopifnot(inherits(BatchPredictRequest, "gar_BatchPredictRequest"))
    
    f(the_body = BatchPredictRequest)
    
}

#' Deploys a model. If a model is already deployed, deploying it with the same parameters has no effect. Deploying with different parametrs (as e.g. changing node_number) will reset the deployment state without pausing the model's availability. Only applicable for Text Classification, Image Object Detection , Tables, and Image Segmentation; all other domains manage deployment automatically. Returns an empty response in the response field when it completes.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/automl}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param DeployModelRequest The \link{DeployModelRequest} object to pass to this method
#' @param name Required
#' @importFrom googleAuthR gar_api_generator
#' @family DeployModelRequest functions
#' @export
projects.locations.models.deploy <- function(DeployModelRequest, name) {
    url <- sprintf("https://automl.googleapis.com/v1/{+name}:deploy", name)
    # automl.projects.locations.models.deploy
    f <- googleAuthR::gar_api_generator(url, "POST", data_parse_function = function(x) x)
    stopifnot(inherits(DeployModelRequest, "gar_DeployModelRequest"))
    
    f(the_body = DeployModelRequest)
    
}

#' Exports a trained, 'export-able', model to a user specified Google Cloud Storage location. A model is considered export-able if and only if it has an export format defined for it in ModelExportOutputConfig. Returns an empty response in the response field when it completes.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/automl}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param ExportModelRequest The \link{ExportModelRequest} object to pass to this method
#' @param name Required
#' @importFrom googleAuthR gar_api_generator
#' @family ExportModelRequest functions
#' @export
projects.locations.models.export <- function(ExportModelRequest, name) {
    url <- sprintf("https://automl.googleapis.com/v1/{+name}:export", name)
    # automl.projects.locations.models.export
    f <- googleAuthR::gar_api_generator(url, "POST", data_parse_function = function(x) x)
    stopifnot(inherits(ExportModelRequest, "gar_ExportModelRequest"))
    
    f(the_body = ExportModelRequest)
    
}

#' Updates a model.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/automl}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param Model The \link{Model} object to pass to this method
#' @param name Output only
#' @param updateMask Required
#' @importFrom googleAuthR gar_api_generator
#' @family Model functions
#' @export
projects.locations.models.patch <- function(Model, name, updateMask = NULL) {
    url <- sprintf("https://automl.googleapis.com/v1/{+name}", name)
    # automl.projects.locations.models.patch
    pars = list(updateMask = updateMask)
    f <- googleAuthR::gar_api_generator(url, "PATCH", pars_args = rmNullObs(pars), 
        data_parse_function = function(x) x)
    stopifnot(inherits(Model, "gar_Model"))
    
    f(the_body = Model)
    
}

#' Perform an online prediction. The prediction result is directly returned in the response. Available for following ML scenarios, and their expected request payloads: AutoML Vision Classification * An image in .JPEG, .GIF or .PNG format, image_bytes up to 30MB. AutoML Vision Object Detection * An image in .JPEG, .GIF or .PNG format, image_bytes up to 30MB. AutoML Natural Language Classification * A TextSnippet up to 60,000 characters, UTF-8 encoded or a document in .PDF, .TIF or .TIFF format with size upto 2MB. AutoML Natural Language Entity Extraction * A TextSnippet up to 10,000 characters, UTF-8 NFC encoded or a document in .PDF, .TIF or .TIFF format with size upto 20MB. AutoML Natural Language Sentiment Analysis * A TextSnippet up to 60,000 characters, UTF-8 encoded or a document in .PDF, .TIF or .TIFF format with size upto 2MB. AutoML Translation * A TextSnippet up to 25,000 characters, UTF-8 encoded. AutoML Tables * A row with column values matching the columns of the model, up to 5MB. Not available for FORECASTING `prediction_type`.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/automl}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param PredictRequest The \link{PredictRequest} object to pass to this method
#' @param name Required
#' @importFrom googleAuthR gar_api_generator
#' @family PredictRequest functions
#' @export
projects.locations.models.predict <- function(PredictRequest, name) {
    url <- sprintf("https://automl.googleapis.com/v1/{+name}:predict", name)
    # automl.projects.locations.models.predict
    f <- googleAuthR::gar_api_generator(url, "POST", data_parse_function = function(x) x)
    stopifnot(inherits(PredictRequest, "gar_PredictRequest"))
    
    f(the_body = PredictRequest)
    
}

#' Lists models.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/automl}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param parent Required
#' @param pageSize Requested page size
#' @param pageToken A token identifying a page of results for the server to return Typically obtained via ListModelsResponse
#' @param filter An expression for filtering the results of the request
#' @importFrom googleAuthR gar_api_generator
#' @export
projects.locations.models.list <- function(parent, pageSize = NULL, pageToken = NULL, 
    filter = NULL) {
    url <- sprintf("https://automl.googleapis.com/v1/{+parent}/models", parent)
    # automl.projects.locations.models.list
    pars = list(pageSize = pageSize, pageToken = pageToken, filter = filter)
    f <- googleAuthR::gar_api_generator(url, "GET", pars_args = rmNullObs(pars), 
        data_parse_function = function(x) x)
    f()
    
}

#' Gets a model.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/automl}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param name Required
#' @importFrom googleAuthR gar_api_generator
#' @export
projects.locations.models.get <- function(name) {
    url <- sprintf("https://automl.googleapis.com/v1/{+name}", name)
    # automl.projects.locations.models.get
    f <- googleAuthR::gar_api_generator(url, "GET", data_parse_function = function(x) x)
    f()
    
}

#' Gets the access control policy for a resource. Returns an empty policy if the resource exists and does not have a policy set.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/automl}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param resource REQUIRED: The resource for which the policy is being requested
#' @param options.requestedPolicyVersion Optional
#' @importFrom googleAuthR gar_api_generator
#' @export
projects.locations.models.getIamPolicy <- function(resource, options.requestedPolicyVersion = NULL) {
    url <- sprintf("https://automl.googleapis.com/v1/{+resource}:getIamPolicy", resource)
    # automl.projects.locations.models.getIamPolicy
    pars = list(options.requestedPolicyVersion = options.requestedPolicyVersion)
    f <- googleAuthR::gar_api_generator(url, "GET", pars_args = rmNullObs(pars), 
        data_parse_function = function(x) x)
    f()
    
}

#' Creates a model. Returns a Model in the response field when it completes. When you create a model, several model evaluations are created for it: a global evaluation, and one evaluation for each annotation spec.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/automl}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param Model The \link{Model} object to pass to this method
#' @param parent Required
#' @importFrom googleAuthR gar_api_generator
#' @family Model functions
#' @export
projects.locations.models.create <- function(Model, parent) {
    url <- sprintf("https://automl.googleapis.com/v1/{+parent}/models", parent)
    # automl.projects.locations.models.create
    f <- googleAuthR::gar_api_generator(url, "POST", data_parse_function = function(x) x)
    stopifnot(inherits(Model, "gar_Model"))
    
    f(the_body = Model)
    
}

#' Sets the access control policy on the specified resource. Replaces any existing policy. Can return `NOT_FOUND`, `INVALID_ARGUMENT`, and `PERMISSION_DENIED` errors.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/automl}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param SetIamPolicyRequest The \link{SetIamPolicyRequest} object to pass to this method
#' @param resource REQUIRED: The resource for which the policy is being specified
#' @importFrom googleAuthR gar_api_generator
#' @family SetIamPolicyRequest functions
#' @export
projects.locations.models.setIamPolicy <- function(SetIamPolicyRequest, resource) {
    url <- sprintf("https://automl.googleapis.com/v1/{+resource}:setIamPolicy", resource)
    # automl.projects.locations.models.setIamPolicy
    f <- googleAuthR::gar_api_generator(url, "POST", data_parse_function = function(x) x)
    stopifnot(inherits(SetIamPolicyRequest, "gar_SetIamPolicyRequest"))
    
    f(the_body = SetIamPolicyRequest)
    
}

#' Lists model evaluations.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/automl}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param parent Required
#' @param filter Required
#' @param pageSize Requested page size
#' @param pageToken A token identifying a page of results for the server to return
#' @importFrom googleAuthR gar_api_generator
#' @export
projects.locations.models.modelEvaluations.list <- function(parent, filter = NULL, 
    pageSize = NULL, pageToken = NULL) {
    url <- sprintf("https://automl.googleapis.com/v1/{+parent}/modelEvaluations", 
        parent)
    # automl.projects.locations.models.modelEvaluations.list
    pars = list(filter = filter, pageSize = pageSize, pageToken = pageToken)
    f <- googleAuthR::gar_api_generator(url, "GET", pars_args = rmNullObs(pars), 
        data_parse_function = function(x) x)
    f()
    
}


#' Gets a model evaluation.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/automl}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param name Required
#' @importFrom googleAuthR gar_api_generator
#' @export


projects.locations.models.modelEvaluations.get <- function(name) {
    
    
    url <- sprintf("https://automl.googleapis.com/v1/{+name}", name)
    # automl.projects.locations.models.modelEvaluations.get
    
    f <- googleAuthR::gar_api_generator(url, "GET", data_parse_function = function(x) x)
    
    f()
    
    
}



