#' Identity Toolkit API
#' The Google Identity Toolkit API lets you use open standards to verify a user's identity.
#' 
#' Auto-generated code by googleAuthR::gar_create_api_skeleton
#'  at 2023-06-21 08:48:24.212216
#' filename: /Users/justinjm/projects/github.com/justinjm/autoGoogleAPI/googleidentitytoolkitv2.auto/R/identitytoolkit_functions.R
#' api_json: api_json
#' 
#' @details 
#' Authentication scopes used are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' \item https://www.googleapis.com/auth/firebase
#' }
#' 
#' @docType package 
#' @name identitytoolkit_googleAuthR
#' 
NULL
## NULL

#' A helper function that tests whether an object is either NULL _or_
#' a list of NULLs
#'
#' @keywords internal
is.NullOb <- function(x) is.null(x) | all(sapply(x, is.null))
#' Recursively step down into list, removing all such objects
#'
#' @keywords internal
rmNullObs <- function(x) {
    x <- Filter(Negate(is.NullOb), x)
    lapply(x, function(x) if (is.list(x))
        rmNullObs(x) else x)
}

#' Revokes a user's token from an Identity Provider (IdP). This is done by manually providing an IdP credential, and the token types for revocation. An [API key](https://cloud.google.com/docs/authentication/api-keys) is required in the request in order to identify the Google Cloud project.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/identity-platform}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param GoogleCloudIdentitytoolkitV2RevokeTokenRequest The \link{GoogleCloudIdentitytoolkitV2RevokeTokenRequest} object to pass to this method
#' #' @importFrom googleAuthR gar_api_generator
#' @family GoogleCloudIdentitytoolkitV2RevokeTokenRequest functions
#' @export
accounts.revokeToken <- function(GoogleCloudIdentitytoolkitV2RevokeTokenRequest) {
    url <- "https://identitytoolkit.googleapis.com/v2/accounts:revokeToken"
    # identitytoolkit.accounts.revokeToken
    f <- googleAuthR::gar_api_generator(url, "POST", data_parse_function = function(x) x)
    stopifnot(inherits(GoogleCloudIdentitytoolkitV2RevokeTokenRequest, "gar_GoogleCloudIdentitytoolkitV2RevokeTokenRequest"))

    f(the_body = GoogleCloudIdentitytoolkitV2RevokeTokenRequest)

}

#' Verifies the MFA challenge and performs sign-in
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/identity-platform}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param GoogleCloudIdentitytoolkitV2FinalizeMfaSignInRequest The \link{GoogleCloudIdentitytoolkitV2FinalizeMfaSignInRequest} object to pass to this method
#' #' @importFrom googleAuthR gar_api_generator
#' @family GoogleCloudIdentitytoolkitV2FinalizeMfaSignInRequest functions
#' @export
accounts.mfaSignIn.finalize <- function(GoogleCloudIdentitytoolkitV2FinalizeMfaSignInRequest) {
    url <- "https://identitytoolkit.googleapis.com/v2/accounts/mfaSignIn:finalize"
    # identitytoolkit.accounts.mfaSignIn.finalize
    f <- googleAuthR::gar_api_generator(url, "POST", data_parse_function = function(x) x)
    stopifnot(inherits(GoogleCloudIdentitytoolkitV2FinalizeMfaSignInRequest, "gar_GoogleCloudIdentitytoolkitV2FinalizeMfaSignInRequest"))

    f(the_body = GoogleCloudIdentitytoolkitV2FinalizeMfaSignInRequest)

}

#' Sends the MFA challenge
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/identity-platform}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param GoogleCloudIdentitytoolkitV2StartMfaSignInRequest The \link{GoogleCloudIdentitytoolkitV2StartMfaSignInRequest} object to pass to this method
#' #' @importFrom googleAuthR gar_api_generator
#' @family GoogleCloudIdentitytoolkitV2StartMfaSignInRequest functions
#' @export
accounts.mfaSignIn.start <- function(GoogleCloudIdentitytoolkitV2StartMfaSignInRequest) {
    url <- "https://identitytoolkit.googleapis.com/v2/accounts/mfaSignIn:start"
    # identitytoolkit.accounts.mfaSignIn.start
    f <- googleAuthR::gar_api_generator(url, "POST", data_parse_function = function(x) x)
    stopifnot(inherits(GoogleCloudIdentitytoolkitV2StartMfaSignInRequest, "gar_GoogleCloudIdentitytoolkitV2StartMfaSignInRequest"))

    f(the_body = GoogleCloudIdentitytoolkitV2StartMfaSignInRequest)

}

#' Revokes one second factor from the enrolled second factors for an account.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/identity-platform}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param GoogleCloudIdentitytoolkitV2WithdrawMfaRequest The \link{GoogleCloudIdentitytoolkitV2WithdrawMfaRequest} object to pass to this method
#' #' @importFrom googleAuthR gar_api_generator
#' @family GoogleCloudIdentitytoolkitV2WithdrawMfaRequest functions
#' @export
accounts.mfaEnrollment.withdraw <- function(GoogleCloudIdentitytoolkitV2WithdrawMfaRequest) {
    url <- "https://identitytoolkit.googleapis.com/v2/accounts/mfaEnrollment:withdraw"
    # identitytoolkit.accounts.mfaEnrollment.withdraw
    f <- googleAuthR::gar_api_generator(url, "POST", data_parse_function = function(x) x)
    stopifnot(inherits(GoogleCloudIdentitytoolkitV2WithdrawMfaRequest, "gar_GoogleCloudIdentitytoolkitV2WithdrawMfaRequest"))

    f(the_body = GoogleCloudIdentitytoolkitV2WithdrawMfaRequest)

}

#' Finishes enrolling a second factor for the user.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/identity-platform}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param GoogleCloudIdentitytoolkitV2FinalizeMfaEnrollmentRequest The \link{GoogleCloudIdentitytoolkitV2FinalizeMfaEnrollmentRequest} object to pass to this method
#' #' @importFrom googleAuthR gar_api_generator
#' @family GoogleCloudIdentitytoolkitV2FinalizeMfaEnrollmentRequest functions
#' @export
accounts.mfaEnrollment.finalize <- function(GoogleCloudIdentitytoolkitV2FinalizeMfaEnrollmentRequest) {
    url <- "https://identitytoolkit.googleapis.com/v2/accounts/mfaEnrollment:finalize"
    # identitytoolkit.accounts.mfaEnrollment.finalize
    f <- googleAuthR::gar_api_generator(url, "POST", data_parse_function = function(x) x)
    stopifnot(inherits(GoogleCloudIdentitytoolkitV2FinalizeMfaEnrollmentRequest,
        "gar_GoogleCloudIdentitytoolkitV2FinalizeMfaEnrollmentRequest"))

    f(the_body = GoogleCloudIdentitytoolkitV2FinalizeMfaEnrollmentRequest)

}

#' Step one of the MFA enrollment process. In SMS case, this sends an SMS verification code to the user.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/identity-platform}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param GoogleCloudIdentitytoolkitV2StartMfaEnrollmentRequest The \link{GoogleCloudIdentitytoolkitV2StartMfaEnrollmentRequest} object to pass to this method
#' #' @importFrom googleAuthR gar_api_generator
#' @family GoogleCloudIdentitytoolkitV2StartMfaEnrollmentRequest functions
#' @export
accounts.mfaEnrollment.start <- function(GoogleCloudIdentitytoolkitV2StartMfaEnrollmentRequest) {
    url <- "https://identitytoolkit.googleapis.com/v2/accounts/mfaEnrollment:start"
    # identitytoolkit.accounts.mfaEnrollment.start
    f <- googleAuthR::gar_api_generator(url, "POST", data_parse_function = function(x) x)
    stopifnot(inherits(GoogleCloudIdentitytoolkitV2StartMfaEnrollmentRequest, "gar_GoogleCloudIdentitytoolkitV2StartMfaEnrollmentRequest"))

    f(the_body = GoogleCloudIdentitytoolkitV2StartMfaEnrollmentRequest)

}

#' Gets password policy config set on the project or tenant.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/identity-platform}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param tenantId The id of a tenant
#' @importFrom googleAuthR gar_api_generator
#' @export
getPasswordPolicy <- function(tenantId = NULL) {
    url <- "https://identitytoolkit.googleapis.com/v2/passwordPolicy"
    # identitytoolkit.getPasswordPolicy
    pars = list(tenantId = tenantId)
    f <- googleAuthR::gar_api_generator(url, "GET", pars_args = rmNullObs(pars),
        data_parse_function = function(x) x)
    f()

}

#' Gets parameters needed for reCAPTCHA analysis.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/identity-platform}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param version The reCAPTCHA version
#' @param clientType reCAPTCHA Enterprise uses separate site keys for different client types
#' @param tenantId The id of a tenant
#' @importFrom googleAuthR gar_api_generator
#' @export
getRecaptchaConfig <- function(version = NULL, clientType = NULL, tenantId = NULL) {
    url <- "https://identitytoolkit.googleapis.com/v2/recaptchaConfig"
    # identitytoolkit.getRecaptchaConfig
    pars = list(version = version, clientType = clientType, tenantId = tenantId)
    f <- googleAuthR::gar_api_generator(url, "GET", pars_args = rmNullObs(pars),
        data_parse_function = function(x) x)
    f()

}

#' Retrieve an Identity Toolkit project configuration.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/identity-platform}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param name The resource name of the config, for example: 'projects/my-awesome-project/config'
#' @importFrom googleAuthR gar_api_generator
#' @export
projects.getConfig <- function(name) {
    url <- sprintf("https://identitytoolkit.googleapis.com/v2/{+name}", name)
    # identitytoolkit.projects.getConfig
    f <- googleAuthR::gar_api_generator(url, "GET", data_parse_function = function(x) x)
    f()

}

#' Update an Identity Toolkit project configuration.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/identity-platform}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' \item https://www.googleapis.com/auth/firebase
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform, https://www.googleapis.com/auth/firebase)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param GoogleCloudIdentitytoolkitAdminV2Config The \link{GoogleCloudIdentitytoolkitAdminV2Config} object to pass to this method
#' @param name Output only
#' @param updateMask The update mask applies to the resource
#' @importFrom googleAuthR gar_api_generator
#' @family GoogleCloudIdentitytoolkitAdminV2Config functions
#' @export
projects.updateConfig <- function(GoogleCloudIdentitytoolkitAdminV2Config, name,
    updateMask = NULL) {
    url <- sprintf("https://identitytoolkit.googleapis.com/v2/{+name}", name)
    # identitytoolkit.projects.updateConfig
    pars = list(updateMask = updateMask)
    f <- googleAuthR::gar_api_generator(url, "PATCH", pars_args = rmNullObs(pars),
        data_parse_function = function(x) x)
    stopifnot(inherits(GoogleCloudIdentitytoolkitAdminV2Config, "gar_GoogleCloudIdentitytoolkitAdminV2Config"))

    f(the_body = GoogleCloudIdentitytoolkitAdminV2Config)

}

#' Retrieve an inbound SAML configuration for an Identity Toolkit project.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/identity-platform}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' \item https://www.googleapis.com/auth/firebase
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform, https://www.googleapis.com/auth/firebase)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param name The resource name of the config, for example: 'projects/my-awesome-project/inboundSamlConfigs/my-config-id'
#' @importFrom googleAuthR gar_api_generator
#' @export
projects.inboundSamlConfigs.get <- function(name) {
    url <- sprintf("https://identitytoolkit.googleapis.com/v2/{+name}", name)
    # identitytoolkit.projects.inboundSamlConfigs.get
    f <- googleAuthR::gar_api_generator(url, "GET", data_parse_function = function(x) x)
    f()

}

#' Update an inbound SAML configuration for an Identity Toolkit project.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/identity-platform}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' \item https://www.googleapis.com/auth/firebase
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform, https://www.googleapis.com/auth/firebase)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param GoogleCloudIdentitytoolkitAdminV2InboundSamlConfig The \link{GoogleCloudIdentitytoolkitAdminV2InboundSamlConfig} object to pass to this method
#' @param name The name of the InboundSamlConfig resource, for example: 'projects/my-awesome-project/inboundSamlConfigs/my-config-id'
#' @param updateMask The update mask applies to the resource
#' @importFrom googleAuthR gar_api_generator
#' @family GoogleCloudIdentitytoolkitAdminV2InboundSamlConfig functions
#' @export
projects.inboundSamlConfigs.patch <- function(GoogleCloudIdentitytoolkitAdminV2InboundSamlConfig,
    name, updateMask = NULL) {
    url <- sprintf("https://identitytoolkit.googleapis.com/v2/{+name}", name)
    # identitytoolkit.projects.inboundSamlConfigs.patch
    pars = list(updateMask = updateMask)
    f <- googleAuthR::gar_api_generator(url, "PATCH", pars_args = rmNullObs(pars),
        data_parse_function = function(x) x)
    stopifnot(inherits(GoogleCloudIdentitytoolkitAdminV2InboundSamlConfig, "gar_GoogleCloudIdentitytoolkitAdminV2InboundSamlConfig"))

    f(the_body = GoogleCloudIdentitytoolkitAdminV2InboundSamlConfig)

}

#' Create an inbound SAML configuration for an Identity Toolkit project.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/identity-platform}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' \item https://www.googleapis.com/auth/firebase
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform, https://www.googleapis.com/auth/firebase)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param GoogleCloudIdentitytoolkitAdminV2InboundSamlConfig The \link{GoogleCloudIdentitytoolkitAdminV2InboundSamlConfig} object to pass to this method
#' @param parent The parent resource name where the config to be created, for example: 'projects/my-awesome-project'
#' @param inboundSamlConfigId The id to use for this config
#' @importFrom googleAuthR gar_api_generator
#' @family GoogleCloudIdentitytoolkitAdminV2InboundSamlConfig functions
#' @export
projects.inboundSamlConfigs.create <- function(GoogleCloudIdentitytoolkitAdminV2InboundSamlConfig,
    parent, inboundSamlConfigId = NULL) {
    url <- sprintf("https://identitytoolkit.googleapis.com/v2/{+parent}/inboundSamlConfigs",
        parent)
    # identitytoolkit.projects.inboundSamlConfigs.create
    pars = list(inboundSamlConfigId = inboundSamlConfigId)
    f <- googleAuthR::gar_api_generator(url, "POST", pars_args = rmNullObs(pars),
        data_parse_function = function(x) x)
    stopifnot(inherits(GoogleCloudIdentitytoolkitAdminV2InboundSamlConfig, "gar_GoogleCloudIdentitytoolkitAdminV2InboundSamlConfig"))

    f(the_body = GoogleCloudIdentitytoolkitAdminV2InboundSamlConfig)

}

#' List all inbound SAML configurations for an Identity Toolkit project.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/identity-platform}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' \item https://www.googleapis.com/auth/firebase
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform, https://www.googleapis.com/auth/firebase)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param parent The parent resource name, for example, 'projects/my-awesome-project'
#' @param pageToken The next_page_token value returned from a previous List request, if any
#' @param pageSize The maximum number of items to return
#' @importFrom googleAuthR gar_api_generator
#' @export
projects.inboundSamlConfigs.list <- function(parent, pageToken = NULL, pageSize = NULL) {
    url <- sprintf("https://identitytoolkit.googleapis.com/v2/{+parent}/inboundSamlConfigs",
        parent)
    # identitytoolkit.projects.inboundSamlConfigs.list
    pars = list(pageToken = pageToken, pageSize = pageSize)
    f <- googleAuthR::gar_api_generator(url, "GET", pars_args = rmNullObs(pars),
        data_parse_function = function(x) x)
    f()

}

#' Delete an inbound SAML configuration for an Identity Toolkit project.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/identity-platform}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' \item https://www.googleapis.com/auth/firebase
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform, https://www.googleapis.com/auth/firebase)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param name The resource name of the config to be deleted, for example: 'projects/my-awesome-project/inboundSamlConfigs/my-config-id'
#' @importFrom googleAuthR gar_api_generator
#' @export
projects.inboundSamlConfigs.delete <- function(name) {
    url <- sprintf("https://identitytoolkit.googleapis.com/v2/{+name}", name)
    # identitytoolkit.projects.inboundSamlConfigs.delete
    f <- googleAuthR::gar_api_generator(url, "DELETE", data_parse_function = function(x) x)
    f()

}

#' Delete a default supported Idp configuration for an Identity Toolkit project.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/identity-platform}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' \item https://www.googleapis.com/auth/firebase
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform, https://www.googleapis.com/auth/firebase)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param name The resource name of the config, for example: 'projects/my-awesome-project/defaultSupportedIdpConfigs/google
#' @importFrom googleAuthR gar_api_generator
#' @export
projects.defaultSupportedIdpConfigs.delete <- function(name) {
    url <- sprintf("https://identitytoolkit.googleapis.com/v2/{+name}", name)
    # identitytoolkit.projects.defaultSupportedIdpConfigs.delete
    f <- googleAuthR::gar_api_generator(url, "DELETE", data_parse_function = function(x) x)
    f()

}

#' Retrieve a default supported Idp configuration for an Identity Toolkit project.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/identity-platform}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' \item https://www.googleapis.com/auth/firebase
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform, https://www.googleapis.com/auth/firebase)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param name The resource name of the config, for example: 'projects/my-awesome-project/defaultSupportedIdpConfigs/google
#' @importFrom googleAuthR gar_api_generator
#' @export
projects.defaultSupportedIdpConfigs.get <- function(name) {
    url <- sprintf("https://identitytoolkit.googleapis.com/v2/{+name}", name)
    # identitytoolkit.projects.defaultSupportedIdpConfigs.get
    f <- googleAuthR::gar_api_generator(url, "GET", data_parse_function = function(x) x)
    f()

}

#' List all default supported Idp configurations for an Identity Toolkit project.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/identity-platform}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' \item https://www.googleapis.com/auth/firebase
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform, https://www.googleapis.com/auth/firebase)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param parent The parent resource name, for example, 'projects/my-awesome-project'
#' @param pageToken The next_page_token value returned from a previous List request, if any
#' @param pageSize The maximum number of items to return
#' @importFrom googleAuthR gar_api_generator
#' @export
projects.defaultSupportedIdpConfigs.list <- function(parent, pageToken = NULL, pageSize = NULL) {
    url <- sprintf("https://identitytoolkit.googleapis.com/v2/{+parent}/defaultSupportedIdpConfigs",
        parent)
    # identitytoolkit.projects.defaultSupportedIdpConfigs.list
    pars = list(pageToken = pageToken, pageSize = pageSize)
    f <- googleAuthR::gar_api_generator(url, "GET", pars_args = rmNullObs(pars),
        data_parse_function = function(x) x)
    f()

}

#' Create a default supported Idp configuration for an Identity Toolkit project.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/identity-platform}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' \item https://www.googleapis.com/auth/firebase
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform, https://www.googleapis.com/auth/firebase)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param GoogleCloudIdentitytoolkitAdminV2DefaultSupportedIdpConfig The \link{GoogleCloudIdentitytoolkitAdminV2DefaultSupportedIdpConfig} object to pass to this method
#' @param parent The parent resource name where the config to be created, for example: 'projects/my-awesome-project'
#' @param idpId The id of the Idp to create a config for
#' @importFrom googleAuthR gar_api_generator
#' @family GoogleCloudIdentitytoolkitAdminV2DefaultSupportedIdpConfig functions
#' @export
projects.defaultSupportedIdpConfigs.create <- function(GoogleCloudIdentitytoolkitAdminV2DefaultSupportedIdpConfig,
    parent, idpId = NULL) {
    url <- sprintf("https://identitytoolkit.googleapis.com/v2/{+parent}/defaultSupportedIdpConfigs",
        parent)
    # identitytoolkit.projects.defaultSupportedIdpConfigs.create
    pars = list(idpId = idpId)
    f <- googleAuthR::gar_api_generator(url, "POST", pars_args = rmNullObs(pars),
        data_parse_function = function(x) x)
    stopifnot(inherits(GoogleCloudIdentitytoolkitAdminV2DefaultSupportedIdpConfig,
        "gar_GoogleCloudIdentitytoolkitAdminV2DefaultSupportedIdpConfig"))

    f(the_body = GoogleCloudIdentitytoolkitAdminV2DefaultSupportedIdpConfig)

}

#' Update a default supported Idp configuration for an Identity Toolkit project.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/identity-platform}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' \item https://www.googleapis.com/auth/firebase
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform, https://www.googleapis.com/auth/firebase)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param GoogleCloudIdentitytoolkitAdminV2DefaultSupportedIdpConfig The \link{GoogleCloudIdentitytoolkitAdminV2DefaultSupportedIdpConfig} object to pass to this method
#' @param name The name of the DefaultSupportedIdpConfig resource, for example: 'projects/my-awesome-project/defaultSupportedIdpConfigs/google
#' @param updateMask The update mask applies to the resource
#' @importFrom googleAuthR gar_api_generator
#' @family GoogleCloudIdentitytoolkitAdminV2DefaultSupportedIdpConfig functions
#' @export
projects.defaultSupportedIdpConfigs.patch <- function(GoogleCloudIdentitytoolkitAdminV2DefaultSupportedIdpConfig,
    name, updateMask = NULL) {
    url <- sprintf("https://identitytoolkit.googleapis.com/v2/{+name}", name)
    # identitytoolkit.projects.defaultSupportedIdpConfigs.patch
    pars = list(updateMask = updateMask)
    f <- googleAuthR::gar_api_generator(url, "PATCH", pars_args = rmNullObs(pars),
        data_parse_function = function(x) x)
    stopifnot(inherits(GoogleCloudIdentitytoolkitAdminV2DefaultSupportedIdpConfig,
        "gar_GoogleCloudIdentitytoolkitAdminV2DefaultSupportedIdpConfig"))

    f(the_body = GoogleCloudIdentitytoolkitAdminV2DefaultSupportedIdpConfig)

}

#' Update an Oidc Idp configuration for an Identity Toolkit project.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/identity-platform}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' \item https://www.googleapis.com/auth/firebase
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform, https://www.googleapis.com/auth/firebase)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param GoogleCloudIdentitytoolkitAdminV2OAuthIdpConfig The \link{GoogleCloudIdentitytoolkitAdminV2OAuthIdpConfig} object to pass to this method
#' @param name The name of the OAuthIdpConfig resource, for example: 'projects/my-awesome-project/oauthIdpConfigs/oauth-config-id'
#' @param updateMask The update mask applies to the resource
#' @importFrom googleAuthR gar_api_generator
#' @family GoogleCloudIdentitytoolkitAdminV2OAuthIdpConfig functions
#' @export
projects.oauthIdpConfigs.patch <- function(GoogleCloudIdentitytoolkitAdminV2OAuthIdpConfig,
    name, updateMask = NULL) {
    url <- sprintf("https://identitytoolkit.googleapis.com/v2/{+name}", name)
    # identitytoolkit.projects.oauthIdpConfigs.patch
    pars = list(updateMask = updateMask)
    f <- googleAuthR::gar_api_generator(url, "PATCH", pars_args = rmNullObs(pars),
        data_parse_function = function(x) x)
    stopifnot(inherits(GoogleCloudIdentitytoolkitAdminV2OAuthIdpConfig, "gar_GoogleCloudIdentitytoolkitAdminV2OAuthIdpConfig"))

    f(the_body = GoogleCloudIdentitytoolkitAdminV2OAuthIdpConfig)

}

#' Create an Oidc Idp configuration for an Identity Toolkit project.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/identity-platform}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' \item https://www.googleapis.com/auth/firebase
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform, https://www.googleapis.com/auth/firebase)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param GoogleCloudIdentitytoolkitAdminV2OAuthIdpConfig The \link{GoogleCloudIdentitytoolkitAdminV2OAuthIdpConfig} object to pass to this method
#' @param parent The parent resource name where the config to be created, for example: 'projects/my-awesome-project'
#' @param oauthIdpConfigId The id to use for this config
#' @importFrom googleAuthR gar_api_generator
#' @family GoogleCloudIdentitytoolkitAdminV2OAuthIdpConfig functions
#' @export
projects.oauthIdpConfigs.create <- function(GoogleCloudIdentitytoolkitAdminV2OAuthIdpConfig,
    parent, oauthIdpConfigId = NULL) {
    url <- sprintf("https://identitytoolkit.googleapis.com/v2/{+parent}/oauthIdpConfigs",
        parent)
    # identitytoolkit.projects.oauthIdpConfigs.create
    pars = list(oauthIdpConfigId = oauthIdpConfigId)
    f <- googleAuthR::gar_api_generator(url, "POST", pars_args = rmNullObs(pars),
        data_parse_function = function(x) x)
    stopifnot(inherits(GoogleCloudIdentitytoolkitAdminV2OAuthIdpConfig, "gar_GoogleCloudIdentitytoolkitAdminV2OAuthIdpConfig"))

    f(the_body = GoogleCloudIdentitytoolkitAdminV2OAuthIdpConfig)

}

#' Delete an Oidc Idp configuration for an Identity Toolkit project.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/identity-platform}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' \item https://www.googleapis.com/auth/firebase
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform, https://www.googleapis.com/auth/firebase)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param name The resource name of the config to be deleted, for example: 'projects/my-awesome-project/oauthIdpConfigs/oauth-config-id'
#' @importFrom googleAuthR gar_api_generator
#' @export
projects.oauthIdpConfigs.delete <- function(name) {
    url <- sprintf("https://identitytoolkit.googleapis.com/v2/{+name}", name)
    # identitytoolkit.projects.oauthIdpConfigs.delete
    f <- googleAuthR::gar_api_generator(url, "DELETE", data_parse_function = function(x) x)
    f()

}

#' Retrieve an Oidc Idp configuration for an Identity Toolkit project.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/identity-platform}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' \item https://www.googleapis.com/auth/firebase
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform, https://www.googleapis.com/auth/firebase)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param name The resource name of the config, for example: 'projects/my-awesome-project/oauthIdpConfigs/oauth-config-id'
#' @importFrom googleAuthR gar_api_generator
#' @export
projects.oauthIdpConfigs.get <- function(name) {
    url <- sprintf("https://identitytoolkit.googleapis.com/v2/{+name}", name)
    # identitytoolkit.projects.oauthIdpConfigs.get
    f <- googleAuthR::gar_api_generator(url, "GET", data_parse_function = function(x) x)
    f()

}

#' List all Oidc Idp configurations for an Identity Toolkit project.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/identity-platform}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' \item https://www.googleapis.com/auth/firebase
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform, https://www.googleapis.com/auth/firebase)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param parent The parent resource name, for example, 'projects/my-awesome-project'
#' @param pageToken The next_page_token value returned from a previous List request, if any
#' @param pageSize The maximum number of items to return
#' @importFrom googleAuthR gar_api_generator
#' @export
projects.oauthIdpConfigs.list <- function(parent, pageToken = NULL, pageSize = NULL) {
    url <- sprintf("https://identitytoolkit.googleapis.com/v2/{+parent}/oauthIdpConfigs",
        parent)
    # identitytoolkit.projects.oauthIdpConfigs.list
    pars = list(pageToken = pageToken, pageSize = pageSize)
    f <- googleAuthR::gar_api_generator(url, "GET", pars_args = rmNullObs(pars),
        data_parse_function = function(x) x)
    f()

}

#' Returns the caller's permissions on a resource. An error is returned if the resource does not exist. A caller is not required to have Google IAM permission to make this request.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/identity-platform}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' \item https://www.googleapis.com/auth/firebase
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform, https://www.googleapis.com/auth/firebase)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param GoogleIamV1TestIamPermissionsRequest The \link{GoogleIamV1TestIamPermissionsRequest} object to pass to this method
#' @param resource REQUIRED: The resource for which the policy detail is being requested
#' @importFrom googleAuthR gar_api_generator
#' @family GoogleIamV1TestIamPermissionsRequest functions
#' @export
projects.tenants.testIamPermissions <- function(GoogleIamV1TestIamPermissionsRequest,
    resource) {
    url <- sprintf("https://identitytoolkit.googleapis.com/v2/{+resource}:testIamPermissions",
        resource)
    # identitytoolkit.projects.tenants.testIamPermissions
    f <- googleAuthR::gar_api_generator(url, "POST", data_parse_function = function(x) x)
    stopifnot(inherits(GoogleIamV1TestIamPermissionsRequest, "gar_GoogleIamV1TestIamPermissionsRequest"))

    f(the_body = GoogleIamV1TestIamPermissionsRequest)

}

#' Get a tenant. Requires read permission on the Tenant resource.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/identity-platform}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' \item https://www.googleapis.com/auth/firebase
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform, https://www.googleapis.com/auth/firebase)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param name Resource name of the tenant to retrieve
#' @importFrom googleAuthR gar_api_generator
#' @export
projects.tenants.get <- function(name) {
    url <- sprintf("https://identitytoolkit.googleapis.com/v2/{+name}", name)
    # identitytoolkit.projects.tenants.get
    f <- googleAuthR::gar_api_generator(url, "GET", data_parse_function = function(x) x)
    f()

}

#' List tenants under the given agent project. Requires read permission on the Agent project.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/identity-platform}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' \item https://www.googleapis.com/auth/firebase
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform, https://www.googleapis.com/auth/firebase)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param parent Required
#' @param pageToken The pagination token from the response of a previous request
#' @param pageSize The maximum number of results to return, capped at 1000
#' @importFrom googleAuthR gar_api_generator
#' @export
projects.tenants.list <- function(parent, pageToken = NULL, pageSize = NULL) {
    url <- sprintf("https://identitytoolkit.googleapis.com/v2/{+parent}/tenants",
        parent)
    # identitytoolkit.projects.tenants.list
    pars = list(pageToken = pageToken, pageSize = pageSize)
    f <- googleAuthR::gar_api_generator(url, "GET", pars_args = rmNullObs(pars),
        data_parse_function = function(x) x)
    f()

}

#' Create a tenant. Requires write permission on the Agent project.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/identity-platform}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' \item https://www.googleapis.com/auth/firebase
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform, https://www.googleapis.com/auth/firebase)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param GoogleCloudIdentitytoolkitAdminV2Tenant The \link{GoogleCloudIdentitytoolkitAdminV2Tenant} object to pass to this method
#' @param parent The parent resource name where the tenant will be created
#' @importFrom googleAuthR gar_api_generator
#' @family GoogleCloudIdentitytoolkitAdminV2Tenant functions
#' @export
projects.tenants.create <- function(GoogleCloudIdentitytoolkitAdminV2Tenant, parent) {
    url <- sprintf("https://identitytoolkit.googleapis.com/v2/{+parent}/tenants",
        parent)
    # identitytoolkit.projects.tenants.create
    f <- googleAuthR::gar_api_generator(url, "POST", data_parse_function = function(x) x)
    stopifnot(inherits(GoogleCloudIdentitytoolkitAdminV2Tenant, "gar_GoogleCloudIdentitytoolkitAdminV2Tenant"))

    f(the_body = GoogleCloudIdentitytoolkitAdminV2Tenant)

}

#' Update a tenant. Requires write permission on the Tenant resource.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/identity-platform}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' \item https://www.googleapis.com/auth/firebase
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform, https://www.googleapis.com/auth/firebase)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param GoogleCloudIdentitytoolkitAdminV2Tenant The \link{GoogleCloudIdentitytoolkitAdminV2Tenant} object to pass to this method
#' @param name Output only
#' @param updateMask If provided, only update fields set in the update mask
#' @importFrom googleAuthR gar_api_generator
#' @family GoogleCloudIdentitytoolkitAdminV2Tenant functions
#' @export
projects.tenants.patch <- function(GoogleCloudIdentitytoolkitAdminV2Tenant, name,
    updateMask = NULL) {
    url <- sprintf("https://identitytoolkit.googleapis.com/v2/{+name}", name)
    # identitytoolkit.projects.tenants.patch
    pars = list(updateMask = updateMask)
    f <- googleAuthR::gar_api_generator(url, "PATCH", pars_args = rmNullObs(pars),
        data_parse_function = function(x) x)
    stopifnot(inherits(GoogleCloudIdentitytoolkitAdminV2Tenant, "gar_GoogleCloudIdentitytoolkitAdminV2Tenant"))

    f(the_body = GoogleCloudIdentitytoolkitAdminV2Tenant)

}

#' Gets the access control policy for a resource. An error is returned if the resource does not exist. An empty policy is returned if the resource exists but does not have a policy set on it. Caller must have the right Google IAM permission on the resource.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/identity-platform}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' \item https://www.googleapis.com/auth/firebase
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform, https://www.googleapis.com/auth/firebase)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param GoogleIamV1GetIamPolicyRequest The \link{GoogleIamV1GetIamPolicyRequest} object to pass to this method
#' @param resource REQUIRED: The resource for which the policy is being requested
#' @importFrom googleAuthR gar_api_generator
#' @family GoogleIamV1GetIamPolicyRequest functions
#' @export
projects.tenants.getIamPolicy <- function(GoogleIamV1GetIamPolicyRequest, resource) {
    url <- sprintf("https://identitytoolkit.googleapis.com/v2/{+resource}:getIamPolicy",
        resource)
    # identitytoolkit.projects.tenants.getIamPolicy
    f <- googleAuthR::gar_api_generator(url, "POST", data_parse_function = function(x) x)
    stopifnot(inherits(GoogleIamV1GetIamPolicyRequest, "gar_GoogleIamV1GetIamPolicyRequest"))

    f(the_body = GoogleIamV1GetIamPolicyRequest)

}

#' Sets the access control policy for a resource. If the policy exists, it is replaced. Caller must have the right Google IAM permission on the resource.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/identity-platform}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' \item https://www.googleapis.com/auth/firebase
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform, https://www.googleapis.com/auth/firebase)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param GoogleIamV1SetIamPolicyRequest The \link{GoogleIamV1SetIamPolicyRequest} object to pass to this method
#' @param resource REQUIRED: The resource for which the policy is being specified
#' @importFrom googleAuthR gar_api_generator
#' @family GoogleIamV1SetIamPolicyRequest functions
#' @export
projects.tenants.setIamPolicy <- function(GoogleIamV1SetIamPolicyRequest, resource) {
    url <- sprintf("https://identitytoolkit.googleapis.com/v2/{+resource}:setIamPolicy",
        resource)
    # identitytoolkit.projects.tenants.setIamPolicy
    f <- googleAuthR::gar_api_generator(url, "POST", data_parse_function = function(x) x)
    stopifnot(inherits(GoogleIamV1SetIamPolicyRequest, "gar_GoogleIamV1SetIamPolicyRequest"))

    f(the_body = GoogleIamV1SetIamPolicyRequest)

}

#' Delete a tenant. Requires write permission on the Agent project.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/identity-platform}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' \item https://www.googleapis.com/auth/firebase
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform, https://www.googleapis.com/auth/firebase)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param name Resource name of the tenant to delete
#' @importFrom googleAuthR gar_api_generator
#' @export
projects.tenants.delete <- function(name) {
    url <- sprintf("https://identitytoolkit.googleapis.com/v2/{+name}", name)
    # identitytoolkit.projects.tenants.delete
    f <- googleAuthR::gar_api_generator(url, "DELETE", data_parse_function = function(x) x)
    f()

}

#' Create an Oidc Idp configuration for an Identity Toolkit project.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/identity-platform}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' \item https://www.googleapis.com/auth/firebase
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform, https://www.googleapis.com/auth/firebase)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param GoogleCloudIdentitytoolkitAdminV2OAuthIdpConfig The \link{GoogleCloudIdentitytoolkitAdminV2OAuthIdpConfig} object to pass to this method
#' @param parent The parent resource name where the config to be created, for example: 'projects/my-awesome-project'
#' @param oauthIdpConfigId The id to use for this config
#' @importFrom googleAuthR gar_api_generator
#' @family GoogleCloudIdentitytoolkitAdminV2OAuthIdpConfig functions
#' @export
projects.tenants.oauthIdpConfigs.create <- function(GoogleCloudIdentitytoolkitAdminV2OAuthIdpConfig,
    parent, oauthIdpConfigId = NULL) {
    url <- sprintf("https://identitytoolkit.googleapis.com/v2/{+parent}/oauthIdpConfigs",
        parent)
    # identitytoolkit.projects.tenants.oauthIdpConfigs.create
    pars = list(oauthIdpConfigId = oauthIdpConfigId)
    f <- googleAuthR::gar_api_generator(url, "POST", pars_args = rmNullObs(pars),
        data_parse_function = function(x) x)
    stopifnot(inherits(GoogleCloudIdentitytoolkitAdminV2OAuthIdpConfig, "gar_GoogleCloudIdentitytoolkitAdminV2OAuthIdpConfig"))

    f(the_body = GoogleCloudIdentitytoolkitAdminV2OAuthIdpConfig)

}

#' Delete an Oidc Idp configuration for an Identity Toolkit project.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/identity-platform}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' \item https://www.googleapis.com/auth/firebase
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform, https://www.googleapis.com/auth/firebase)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param name The resource name of the config to be deleted, for example: 'projects/my-awesome-project/oauthIdpConfigs/oauth-config-id'
#' @importFrom googleAuthR gar_api_generator
#' @export
projects.tenants.oauthIdpConfigs.delete <- function(name) {
    url <- sprintf("https://identitytoolkit.googleapis.com/v2/{+name}", name)
    # identitytoolkit.projects.tenants.oauthIdpConfigs.delete
    f <- googleAuthR::gar_api_generator(url, "DELETE", data_parse_function = function(x) x)
    f()

}

#' Update an Oidc Idp configuration for an Identity Toolkit project.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/identity-platform}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' \item https://www.googleapis.com/auth/firebase
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform, https://www.googleapis.com/auth/firebase)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param GoogleCloudIdentitytoolkitAdminV2OAuthIdpConfig The \link{GoogleCloudIdentitytoolkitAdminV2OAuthIdpConfig} object to pass to this method
#' @param name The name of the OAuthIdpConfig resource, for example: 'projects/my-awesome-project/oauthIdpConfigs/oauth-config-id'
#' @param updateMask The update mask applies to the resource
#' @importFrom googleAuthR gar_api_generator
#' @family GoogleCloudIdentitytoolkitAdminV2OAuthIdpConfig functions
#' @export
projects.tenants.oauthIdpConfigs.patch <- function(GoogleCloudIdentitytoolkitAdminV2OAuthIdpConfig,
    name, updateMask = NULL) {
    url <- sprintf("https://identitytoolkit.googleapis.com/v2/{+name}", name)
    # identitytoolkit.projects.tenants.oauthIdpConfigs.patch
    pars = list(updateMask = updateMask)
    f <- googleAuthR::gar_api_generator(url, "PATCH", pars_args = rmNullObs(pars),
        data_parse_function = function(x) x)
    stopifnot(inherits(GoogleCloudIdentitytoolkitAdminV2OAuthIdpConfig, "gar_GoogleCloudIdentitytoolkitAdminV2OAuthIdpConfig"))

    f(the_body = GoogleCloudIdentitytoolkitAdminV2OAuthIdpConfig)

}

#' Retrieve an Oidc Idp configuration for an Identity Toolkit project.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/identity-platform}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' \item https://www.googleapis.com/auth/firebase
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform, https://www.googleapis.com/auth/firebase)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param name The resource name of the config, for example: 'projects/my-awesome-project/oauthIdpConfigs/oauth-config-id'
#' @importFrom googleAuthR gar_api_generator
#' @export
projects.tenants.oauthIdpConfigs.get <- function(name) {
    url <- sprintf("https://identitytoolkit.googleapis.com/v2/{+name}", name)
    # identitytoolkit.projects.tenants.oauthIdpConfigs.get
    f <- googleAuthR::gar_api_generator(url, "GET", data_parse_function = function(x) x)
    f()

}

#' List all Oidc Idp configurations for an Identity Toolkit project.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/identity-platform}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' \item https://www.googleapis.com/auth/firebase
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform, https://www.googleapis.com/auth/firebase)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param parent The parent resource name, for example, 'projects/my-awesome-project'
#' @param pageToken The next_page_token value returned from a previous List request, if any
#' @param pageSize The maximum number of items to return
#' @importFrom googleAuthR gar_api_generator
#' @export
projects.tenants.oauthIdpConfigs.list <- function(parent, pageToken = NULL, pageSize = NULL) {
    url <- sprintf("https://identitytoolkit.googleapis.com/v2/{+parent}/oauthIdpConfigs",
        parent)
    # identitytoolkit.projects.tenants.oauthIdpConfigs.list
    pars = list(pageToken = pageToken, pageSize = pageSize)
    f <- googleAuthR::gar_api_generator(url, "GET", pars_args = rmNullObs(pars),
        data_parse_function = function(x) x)
    f()

}

#' Retrieve a default supported Idp configuration for an Identity Toolkit project.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/identity-platform}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' \item https://www.googleapis.com/auth/firebase
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform, https://www.googleapis.com/auth/firebase)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param name The resource name of the config, for example: 'projects/my-awesome-project/defaultSupportedIdpConfigs/google
#' @importFrom googleAuthR gar_api_generator
#' @export
projects.tenants.defaultSupportedIdpConfigs.get <- function(name) {
    url <- sprintf("https://identitytoolkit.googleapis.com/v2/{+name}", name)
    # identitytoolkit.projects.tenants.defaultSupportedIdpConfigs.get
    f <- googleAuthR::gar_api_generator(url, "GET", data_parse_function = function(x) x)
    f()

}

#' Create a default supported Idp configuration for an Identity Toolkit project.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/identity-platform}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' \item https://www.googleapis.com/auth/firebase
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform, https://www.googleapis.com/auth/firebase)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param GoogleCloudIdentitytoolkitAdminV2DefaultSupportedIdpConfig The \link{GoogleCloudIdentitytoolkitAdminV2DefaultSupportedIdpConfig} object to pass to this method
#' @param parent The parent resource name where the config to be created, for example: 'projects/my-awesome-project'
#' @param idpId The id of the Idp to create a config for
#' @importFrom googleAuthR gar_api_generator
#' @family GoogleCloudIdentitytoolkitAdminV2DefaultSupportedIdpConfig functions
#' @export
projects.tenants.defaultSupportedIdpConfigs.create <- function(GoogleCloudIdentitytoolkitAdminV2DefaultSupportedIdpConfig,
    parent, idpId = NULL) {
    url <- sprintf("https://identitytoolkit.googleapis.com/v2/{+parent}/defaultSupportedIdpConfigs",
        parent)
    # identitytoolkit.projects.tenants.defaultSupportedIdpConfigs.create
    pars = list(idpId = idpId)
    f <- googleAuthR::gar_api_generator(url, "POST", pars_args = rmNullObs(pars),
        data_parse_function = function(x) x)
    stopifnot(inherits(GoogleCloudIdentitytoolkitAdminV2DefaultSupportedIdpConfig,
        "gar_GoogleCloudIdentitytoolkitAdminV2DefaultSupportedIdpConfig"))

    f(the_body = GoogleCloudIdentitytoolkitAdminV2DefaultSupportedIdpConfig)

}

#' Delete a default supported Idp configuration for an Identity Toolkit project.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/identity-platform}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' \item https://www.googleapis.com/auth/firebase
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform, https://www.googleapis.com/auth/firebase)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param name The resource name of the config, for example: 'projects/my-awesome-project/defaultSupportedIdpConfigs/google
#' @importFrom googleAuthR gar_api_generator
#' @export
projects.tenants.defaultSupportedIdpConfigs.delete <- function(name) {
    url <- sprintf("https://identitytoolkit.googleapis.com/v2/{+name}", name)
    # identitytoolkit.projects.tenants.defaultSupportedIdpConfigs.delete
    f <- googleAuthR::gar_api_generator(url, "DELETE", data_parse_function = function(x) x)
    f()

}

#' Update a default supported Idp configuration for an Identity Toolkit project.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/identity-platform}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' \item https://www.googleapis.com/auth/firebase
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform, https://www.googleapis.com/auth/firebase)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param GoogleCloudIdentitytoolkitAdminV2DefaultSupportedIdpConfig The \link{GoogleCloudIdentitytoolkitAdminV2DefaultSupportedIdpConfig} object to pass to this method
#' @param name The name of the DefaultSupportedIdpConfig resource, for example: 'projects/my-awesome-project/defaultSupportedIdpConfigs/google
#' @param updateMask The update mask applies to the resource
#' @importFrom googleAuthR gar_api_generator
#' @family GoogleCloudIdentitytoolkitAdminV2DefaultSupportedIdpConfig functions
#' @export
projects.tenants.defaultSupportedIdpConfigs.patch <- function(GoogleCloudIdentitytoolkitAdminV2DefaultSupportedIdpConfig,
    name, updateMask = NULL) {
    url <- sprintf("https://identitytoolkit.googleapis.com/v2/{+name}", name)
    # identitytoolkit.projects.tenants.defaultSupportedIdpConfigs.patch
    pars = list(updateMask = updateMask)
    f <- googleAuthR::gar_api_generator(url, "PATCH", pars_args = rmNullObs(pars),
        data_parse_function = function(x) x)
    stopifnot(inherits(GoogleCloudIdentitytoolkitAdminV2DefaultSupportedIdpConfig,
        "gar_GoogleCloudIdentitytoolkitAdminV2DefaultSupportedIdpConfig"))

    f(the_body = GoogleCloudIdentitytoolkitAdminV2DefaultSupportedIdpConfig)

}

#' List all default supported Idp configurations for an Identity Toolkit project.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/identity-platform}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' \item https://www.googleapis.com/auth/firebase
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform, https://www.googleapis.com/auth/firebase)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param parent The parent resource name, for example, 'projects/my-awesome-project'
#' @param pageSize The maximum number of items to return
#' @param pageToken The next_page_token value returned from a previous List request, if any
#' @importFrom googleAuthR gar_api_generator
#' @export
projects.tenants.defaultSupportedIdpConfigs.list <- function(parent, pageSize = NULL,
    pageToken = NULL) {
    url <- sprintf("https://identitytoolkit.googleapis.com/v2/{+parent}/defaultSupportedIdpConfigs",
        parent)
    # identitytoolkit.projects.tenants.defaultSupportedIdpConfigs.list
    pars = list(pageSize = pageSize, pageToken = pageToken)
    f <- googleAuthR::gar_api_generator(url, "GET", pars_args = rmNullObs(pars),
        data_parse_function = function(x) x)
    f()

}

#' Update an inbound SAML configuration for an Identity Toolkit project.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/identity-platform}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' \item https://www.googleapis.com/auth/firebase
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform, https://www.googleapis.com/auth/firebase)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param GoogleCloudIdentitytoolkitAdminV2InboundSamlConfig The \link{GoogleCloudIdentitytoolkitAdminV2InboundSamlConfig} object to pass to this method
#' @param name The name of the InboundSamlConfig resource, for example: 'projects/my-awesome-project/inboundSamlConfigs/my-config-id'
#' @param updateMask The update mask applies to the resource
#' @importFrom googleAuthR gar_api_generator
#' @family GoogleCloudIdentitytoolkitAdminV2InboundSamlConfig functions
#' @export
projects.tenants.inboundSamlConfigs.patch <- function(GoogleCloudIdentitytoolkitAdminV2InboundSamlConfig,
    name, updateMask = NULL) {
    url <- sprintf("https://identitytoolkit.googleapis.com/v2/{+name}", name)
    # identitytoolkit.projects.tenants.inboundSamlConfigs.patch
    pars = list(updateMask = updateMask)
    f <- googleAuthR::gar_api_generator(url, "PATCH", pars_args = rmNullObs(pars),
        data_parse_function = function(x) x)
    stopifnot(inherits(GoogleCloudIdentitytoolkitAdminV2InboundSamlConfig, "gar_GoogleCloudIdentitytoolkitAdminV2InboundSamlConfig"))

    f(the_body = GoogleCloudIdentitytoolkitAdminV2InboundSamlConfig)

}

#' List all inbound SAML configurations for an Identity Toolkit project.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/identity-platform}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' \item https://www.googleapis.com/auth/firebase
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform, https://www.googleapis.com/auth/firebase)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param parent The parent resource name, for example, 'projects/my-awesome-project'
#' @param pageToken The next_page_token value returned from a previous List request, if any
#' @param pageSize The maximum number of items to return
#' @importFrom googleAuthR gar_api_generator
#' @export
projects.tenants.inboundSamlConfigs.list <- function(parent, pageToken = NULL, pageSize = NULL) {
    url <- sprintf("https://identitytoolkit.googleapis.com/v2/{+parent}/inboundSamlConfigs",
        parent)
    # identitytoolkit.projects.tenants.inboundSamlConfigs.list
    pars = list(pageToken = pageToken, pageSize = pageSize)
    f <- googleAuthR::gar_api_generator(url, "GET", pars_args = rmNullObs(pars),
        data_parse_function = function(x) x)
    f()

}

#' Delete an inbound SAML configuration for an Identity Toolkit project.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/identity-platform}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' \item https://www.googleapis.com/auth/firebase
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform, https://www.googleapis.com/auth/firebase)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param name The resource name of the config to be deleted, for example: 'projects/my-awesome-project/inboundSamlConfigs/my-config-id'
#' @importFrom googleAuthR gar_api_generator
#' @export
projects.tenants.inboundSamlConfigs.delete <- function(name) {
    url <- sprintf("https://identitytoolkit.googleapis.com/v2/{+name}", name)
    # identitytoolkit.projects.tenants.inboundSamlConfigs.delete
    f <- googleAuthR::gar_api_generator(url, "DELETE", data_parse_function = function(x) x)
    f()

}

#' Create an inbound SAML configuration for an Identity Toolkit project.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/identity-platform}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' \item https://www.googleapis.com/auth/firebase
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform, https://www.googleapis.com/auth/firebase)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param GoogleCloudIdentitytoolkitAdminV2InboundSamlConfig The \link{GoogleCloudIdentitytoolkitAdminV2InboundSamlConfig} object to pass to this method
#' @param parent The parent resource name where the config to be created, for example: 'projects/my-awesome-project'
#' @param inboundSamlConfigId The id to use for this config
#' @importFrom googleAuthR gar_api_generator
#' @family GoogleCloudIdentitytoolkitAdminV2InboundSamlConfig functions
#' @export
projects.tenants.inboundSamlConfigs.create <- function(GoogleCloudIdentitytoolkitAdminV2InboundSamlConfig,
    parent, inboundSamlConfigId = NULL) {
    url <- sprintf("https://identitytoolkit.googleapis.com/v2/{+parent}/inboundSamlConfigs",
        parent)
    # identitytoolkit.projects.tenants.inboundSamlConfigs.create
    pars = list(inboundSamlConfigId = inboundSamlConfigId)
    f <- googleAuthR::gar_api_generator(url, "POST", pars_args = rmNullObs(pars),
        data_parse_function = function(x) x)
    stopifnot(inherits(GoogleCloudIdentitytoolkitAdminV2InboundSamlConfig, "gar_GoogleCloudIdentitytoolkitAdminV2InboundSamlConfig"))

    f(the_body = GoogleCloudIdentitytoolkitAdminV2InboundSamlConfig)

}

#' Retrieve an inbound SAML configuration for an Identity Toolkit project.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/identity-platform}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' \item https://www.googleapis.com/auth/firebase
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform, https://www.googleapis.com/auth/firebase)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param name The resource name of the config, for example: 'projects/my-awesome-project/inboundSamlConfigs/my-config-id'
#' @importFrom googleAuthR gar_api_generator
#' @export
projects.tenants.inboundSamlConfigs.get <- function(name) {
    url <- sprintf("https://identitytoolkit.googleapis.com/v2/{+name}", name)
    # identitytoolkit.projects.tenants.inboundSamlConfigs.get
    f <- googleAuthR::gar_api_generator(url, "GET", data_parse_function = function(x) x)
    f()

}

#' Initialize Identity Platform for a Cloud project. Identity Platform is an end-to-end authentication system for third-party users to access your apps and services. These could include mobile/web apps, games, APIs and beyond. This is the publicly available variant of EnableIdentityPlatform that is only available to billing-enabled projects.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/identity-platform}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param GoogleCloudIdentitytoolkitAdminV2InitializeIdentityPlatformRequest The \link{GoogleCloudIdentitytoolkitAdminV2InitializeIdentityPlatformRequest} object to pass to this method
#' @param project The resource name of the target project the developer wants to enable Identity Platform for
#' @importFrom googleAuthR gar_api_generator
#' @family GoogleCloudIdentitytoolkitAdminV2InitializeIdentityPlatformRequest functions
#' @export
projects.identityPlatform.initializeAuth <- function(GoogleCloudIdentitytoolkitAdminV2InitializeIdentityPlatformRequest,
    project) {
    url <- sprintf("https://identitytoolkit.googleapis.com/v2/{+project}/identityPlatform:initializeAuth",
        project)
    # identitytoolkit.projects.identityPlatform.initializeAuth
    f <- googleAuthR::gar_api_generator(url, "POST", data_parse_function = function(x) x)
    stopifnot(inherits(GoogleCloudIdentitytoolkitAdminV2InitializeIdentityPlatformRequest,
        "gar_GoogleCloudIdentitytoolkitAdminV2InitializeIdentityPlatformRequest"))

    f(the_body = GoogleCloudIdentitytoolkitAdminV2InitializeIdentityPlatformRequest)

}


#' List all default supported Idps.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/identity-platform}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' \item https://www.googleapis.com/auth/firebase
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform, https://www.googleapis.com/auth/firebase)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param pageToken The next_page_token value returned from a previous List request, if any

#' @param pageSize The maximum number of items to return
#' @importFrom googleAuthR gar_api_generator
#' @export


defaultSupportedIdps.list <- function(pageToken = NULL, pageSize = NULL) {


    url <- "https://identitytoolkit.googleapis.com/v2/defaultSupportedIdps"
    # identitytoolkit.defaultSupportedIdps.list
    pars = list(pageToken = pageToken, pageSize = pageSize)

    f <- googleAuthR::gar_api_generator(url, "GET", pars_args = rmNullObs(pars),
        data_parse_function = function(x) x)

    f()


}



